# SHARKS CLEANING - ATTACKS TO MEN SINCE 2001

In [1]:
'''
%pip install ipython
%pip install seaborn
'''

'\n%pip install ipython\n%pip install seaborn\n'

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

import warnings
warnings.filterwarnings('ignore')

import pylab as plt
import seaborn as sns

%matplotlib inline

In [3]:
sharks = pd.read_csv('../DATA/attacks.csv', encoding = "ISO-8859-1")

In [4]:
sharks.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [5]:
sharks_ori_shape = sharks.shape
sharks_ori_shape

(25723, 24)

In [6]:
sharks.tail(20)  # podemos observar que al final de nuestro dataframe, hay muchas filas que no tienen ningún dato

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
25703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
sharks = sharks.dropna(how = 'all') # eliminamos las filas que tengan todo nulo

In [8]:
sharks.shape, sharks_ori_shape # tamaño del df ahora vs al inicio

((8703, 24), (25723, 24))

In [9]:
sharks # vemos que todavía tenemos muchas filas con muchos nulos

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8698,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8700,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
sharks = sharks[sharks.isna().sum(axis=1) < 10]

In [11]:
sharks

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [12]:
sharks.shape, sharks_ori_shape # tamaño del df ahora vs al inicio

((6295, 24), (25723, 24))

In [13]:
sharks.info() # vemos las columnas con su tipo de variable y los no nulos que tienen cada una

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6295 entries, 0 to 6301
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             6294 non-null   object
 1   Date                    6295 non-null   object
 2   Year                    6293 non-null   float64
 3   Type                    6291 non-null   object
 4   Country                 6246 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5761 non-null   object
 7   Activity                5757 non-null   object
 8   Name                    6090 non-null   object
 9   Sex                     5736 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6269 non-null   object
 12  Fatal (Y/N)             5759 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3462 non-null   object
 15  Investigator or Source  6279 non-null   object
 16  pdf                     6295 non-null   object
 17  href formula            6294 non-null   object
 18  href                    6295 non-null   object
 19  Case Number.1           6295 non-null   object
 20  Case Number.2           6295 non-null   object
 21  original order          6295 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 1.2+ MB

In [14]:
# Las columnas Unnamed: 22 y Unnamed: 23 tendríamos que rellenarlas con datos, en este caso, al ser de tipo Object, con un String 'desconocido'

In [15]:
sharks[['Unnamed: 22', 'Unnamed: 23']] = sharks[['Unnamed: 22', 'Unnamed: 23']].fillna('Unknown')

In [16]:
nanCols = sharks.isna().sum()
nanCols[nanCols > 0]

Case Number                  1
Year                         2
Type                         4
Country                     49
Area                       448
Location                   534
Activity                   538
Name                       205
Sex                        559
Age                       2824
Injury                      26
Fatal (Y/N)                536
Time                      3347
Species                   2833
Investigator or Source      16
href formula                 1
dtype: int64

In [17]:
nanCols = sharks.isna().sum()
nanCols[nanCols > 1000]

Age         2824
Time        3347
Species     2833
dtype: int64

In [18]:
# Mirando los valores no nulos, deberíamos mirar la columna 'age', la columna 'time' y la columna 'species'

In [19]:
sharks[['Age','Time','Species ']]

      Age           Time         Species
0      57          18h00      White shark
1      11  14h00  -15h00              NaN
2      48          07h45              NaN
3     NaN            NaN        2 m shark
4     NaN            NaN  Tiger shark, 3m
...   ...            ...              ...
6297  NaN            NaN              NaN
6298  NaN            NaN              NaN
6299  NaN            NaN              NaN
6300  NaN            NaN              NaN
6301   15            NaN              NaN

[6295 rows x 3 columns]

In [20]:
# La columna species tiene un espacio, sería conveniente mirar todos los nombres de columnas y cambiarlos para que tuvieran el mismo formato

In [21]:
columns_names = sharks.columns.values
columns_names

array(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area',
       'Location', 'Activity', 'Name', 'Sex ', 'Age', 'Injury',
       'Fatal (Y/N)', 'Time', 'Species ', 'Investigator or Source', 'pdf',
       'href formula', 'href', 'Case Number.1', 'Case Number.2',
       'original order', 'Unnamed: 22', 'Unnamed: 23'], dtype=object)

In [22]:
sharks.rename(columns={'Case Number': 'caseNumber', 'Date': 'date', 'Year': 'year', 'Type': 'type', 'Country': 'country', 'Area': 'area',
       'Location': 'location', 'Activity': 'activity', 'Name': 'name', 'Sex ': 'sex', 'Age': 'age', 'Injury': 'injury',
       'Fatal (Y/N)': 'fatal(y/n)', 'Time': 'time', 'Species ': 'species', 'Investigator or Source': 'investigatorOrSource', 'pdf': 'pdf',
       'href formula': 'hrefFormula', 'href': 'href', 'Case Number.1': 'caseNumber1', 'Case Number.2': 'caseNumber2',
       'original order': 'originalOrder', 'Unnamed: 22': 'unnamed22', 'Unnamed: 23': 'unnamed23'}, inplace=True)

In [23]:
print(sharks['year'].unique())

[2018. 2017.   nan 2016. 2015. 2014. 2013. 2012. 2011. 2010. 2009. 2008.
 2007. 2006. 2005. 2004. 2003. 2002. 2001. 2000. 1999. 1998. 1997. 1996.
 1995. 1984. 1994. 1993. 1992. 1991. 1990. 1989. 1969. 1988. 1987. 1986.
 1985. 1983. 1982. 1981. 1980. 1979. 1978. 1977. 1976. 1975. 1974. 1973.
 1972. 1971. 1970. 1968. 1967. 1966. 1965. 1964. 1963. 1962. 1961. 1960.
 1959. 1958. 1957. 1956. 1955. 1954. 1953. 1952. 1951. 1950. 1949. 1948.
 1848. 1947. 1946. 1945. 1944. 1943. 1942. 1941. 1940. 1939. 1938. 1937.
 1936. 1935. 1934. 1933. 1932. 1931. 1930. 1929. 1928. 1927. 1926. 1925.
 1924. 1923. 1922. 1921. 1920. 1919. 1918. 1917. 1916. 1915. 1914. 1913.
 1912. 1911. 1910. 1909. 1908. 1907. 1906. 1905. 1904. 1903. 1902. 1901.
 1900. 1899. 1898. 1897. 1896. 1895. 1894. 1893. 1892. 1891. 1890. 1889.
 1888. 1887. 1886. 1885. 1884. 1883. 1882. 1881. 1880. 1879. 1878. 1877.
 1876. 1875. 1874. 1873. 1872. 1871. 1870. 1869. 1868. 1867. 1866. 1865.
 1864. 1863. 1862. 1861. 1860. 1859. 1858. 1857. 1856. 1855. 1853. 1852.
 1851. 1850. 1849. 1847. 1846. 1845. 1844. 1842. 1841. 1840. 1839. 1837.
 1836. 1835. 1834. 1832. 1831. 1830. 1829. 1828. 1827. 1826. 1825. 1822.
 1819. 1818. 1817. 1816. 1815. 1812. 1811. 1810. 1808. 1807. 1805. 1804.
 1803. 1801. 1800. 1797. 1792. 1791. 1788. 1787. 1786. 1785. 1784. 1783.
 1780. 1779. 1776. 1771. 1767. 1764. 1758. 1753. 1751. 1749. 1755. 1748.
 1742. 1738. 1733. 1723. 1721. 1703. 1700. 1642. 1637. 1617. 1595. 1580.
 1555. 1554. 1543.  500.   77.    5.    0.]

In [24]:
print(sharks['sex'].unique())

['F' 'M' nan 'M ' 'lli' 'N' '.']

In [25]:
sharks.shape, sharks_ori_shape # tamaño del df ahora vs al inicio

((6295, 24), (25723, 24))

In [26]:
indexNames = sharks[ sharks['year'] < 2001 ].index # índices de los ataques antes de 2001
sharks.drop(indexNames, inplace=True) # quitamos de nuestro dataframe los índices que hemos hallado previamente
indexNames = sharks[ sharks['sex'] == 'F' ].index # índices de los ataques a mujeres
sharks.drop(indexNames, inplace=True) # quitamos de nuestro dataframe los índices que hemos hallado previamente
indexNames = sharks[ sharks['sex'] == 'lli' ].index # índices de los ataques a otros
sharks.drop(indexNames, inplace=True) # quitamos de nuestro dataframe los índices que hemos hallado previamente

In [27]:
sharks = sharks[sharks['year'].notna()]
sharks = sharks[sharks['sex'].notna()]

In [28]:
sharks.sex = sharks.sex.str.replace('M ', 'M') # para poner todos los datos de género con el mismo formato

In [29]:
print(sharks['year'].unique())

[2018. 2017. 2016. 2015. 2014. 2013. 2012. 2011. 2010. 2009. 2008. 2007.
 2006. 2005. 2004. 2003. 2002. 2001.]

In [30]:
print(sharks['sex'].unique())

['M']

In [31]:
sharks.shape, sharks_ori_shape # tamaño del df solo con los datos de los ataques a hombres desde 2001 vs al inicio

((1558, 24), (25723, 24))

In [32]:
nanCols = sharks.isna().sum()
nanCols[nanCols > 0]

type                      2
country                   2
area                     67
location                 71
activity                 52
name                      9
age                     347
injury                    1
fatal(y/n)              114
time                    428
species                 528
investigatorOrSource      5
dtype: int64

In [33]:
print(sharks['type'].unique())

['Invalid' 'Unprovoked' 'Provoked' 'Questionable' nan 'Boating' 'Boat'
 'Sea Disaster' 'Boatomg']

In [34]:
sharks.type = sharks.type.str.replace('Boating', 'Boat')
sharks.type = sharks.type.str.replace('Boatomg', 'Boat')
sharks.type = sharks.type.str.replace('Boat', 'Boating')

In [35]:
print(sharks['type'].unique())

['Invalid' 'Unprovoked' 'Provoked' 'Questionable' nan 'Boating'
 'Sea Disaster']

In [36]:
display(sharks[sharks['type'].isnull()]) # para ver qué ocurre con los valores nulos de type

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
85,2017.09.15.a,15-Sep-2017,2017.0,NaN,SAMOA,Upolu Island,Nofoalii,Fishing,male,M,NaN,Injuries to hands and legs,N,Night,NaN,"Samoa Observer, 9/16/2017",2017.09.15.a-Samoa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.a,2017.09.15.a,6218.0,Unknown,Unknown
382,2015.07.27,27-Jul-2015,2015.0,NaN,AUSTRALIA,Victoria,Tyrendarra Beach,Surfing,male,M,40,Injury to hand,NaN,NaN,NaN,NaN,2015.07.27-Victoria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.27,2015.07.27,5921.0,Unknown,Unknown

In [37]:
sharks.loc[85,'type'] = ['Unprovoked']
sharks.loc[382,'type'] = ['Unprovoked']

In [38]:
print(sharks['country'].unique())

['USA' 'AUSTRALIA' 'MEXICO' 'BRAZIL' 'ENGLAND' 'SOUTH AFRICA' 'THAILAND'
 'COSTA RICA' 'MALDIVES' 'BAHAMAS' 'ECUADOR' 'NEW CALEDONIA' 'MALAYSIA'
 nan 'CUBA' 'MAURITIUS' 'NEW ZEALAND' 'SPAIN' 'SAMOA' 'SOLOMON ISLANDS'
 'JAPAN' 'ST HELENA, British overseas territory' 'REUNION'
 'FRENCH POLYNESIA' 'UNITED KINGDOM' 'UNITED ARAB EMIRATES' 'PHILIPPINES'
 'INDONESIA' 'CHINA' 'COLUMBIA' 'EGYPT' 'CAPE VERDE' 'Fiji'
 'CAYMAN ISLANDS' 'ARUBA' 'MOZAMBIQUE' 'FIJI' 'PUERTO RICO' 'ITALY'
 'ST. MARTIN' 'FRANCE' 'PAPUA NEW GUINEA' 'TRINIDAD & TOBAGO' 'KIRIBATI'
 'ISRAEL' 'DIEGO GARCIA' 'TAIWAN' 'JAMAICA' 'PALESTINIAN TERRITORIES'
 'GUAM' 'SEYCHELLES' 'SCOTLAND' 'SAUDI ARABIA' 'CHILE' 'ANTIGUA'
 'DOMINICAN REPUBLIC' 'KENYA' 'RUSSIA' 'TURKS & CAICOS'
 'UNITED ARAB EMIRATES (UAE)' 'AZORES' 'TONGA' 'MALTA' 'VIETNAM'
 'MADAGASCAR' 'SOMALIA' 'NEVIS' 'CROATIA' 'PANAMA'
 'BRITISH VIRGIN ISLANDS' 'NORWAY' 'BELIZE' 'Sierra Leone'
 'ATLANTIC OCEAN' 'ST. MAARTIN' 'Seychelles' 'LIBERIA' 'MEXICO '
 'VENEZUELA' 'VANUATU' ' TONGA' 'URUGUAY' 'INDIA' 'MICRONESIA']

In [39]:
sharks['country'] = sharks['country'].str.lower()

In [40]:
display(sharks[sharks['country'].isnull()])

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
62,2017.11.13.R,Reported 13-Nov-2017,2017.0,Unprovoked,NaN,NaN,NaN,Surfing,Timur Yunusov,M,24,Puncture wounds to feet,N,NaN,NaN,Instagram,2017.11.13.R-Timur.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.13.R,2017.11.13.R,6241.0,Unknown,Unknown
525,2014.08.00,Aug-2014,2014.0,Invalid,NaN,NaN,NaN,Sea disaster,Cuban refugees,M,NaN,Shark involvement prior to death not confirmed,NaN,NaN,Shark involvement not confirmed,"Associated Press, 11/27/2014",2014.08.00-Cuban-refugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.08.00,2014.08.00,5778.0,Unknown,Unknown

In [41]:
sharks.loc[62,'country'] = ['Unknown']
sharks.loc[525,'country'] = ['Unknown']

In [42]:
sharks[['name']] = sharks[['name']].fillna('Unknown')

In [43]:
print(sharks['age'].unique())

['48' nan '18' '52' '15' '12' '32' '10' '21' '30' '60' '33' '29' '54' '34'
 '41' '37' '56' '19' '25' '69' '38' '35' '45' '14' '40s' '28' '20' '24'
 '26' '22' '7' '31' '17' '13' '42' '40' '50' '46' '82' '73' '68' '16' '39'
 '58' 'Teen' '55' '57' '47' '61' '65' '36' '43' '60s' '9' '49' '72' '59'
 '11' '27' '64' '23' '71' '44' '62' '6' '63' '70' '18 months' '53' '50s'
 '8' '51' 'teen' '66' '77' '74' '3' '28 & 26' '30s' '5' '86' '12 or 13'
 '46 & 34' 'Teens' '84' '\xa0 ' ' ' '30 or 36' '6½' '21 & ?' '75'
 '33 or 37' 'mid-30s']

In [44]:
sharks[['age']] = sharks[['age']].fillna('-1')

In [45]:
sharks.age = sharks.age.str.replace('40s', '40')
sharks.age = sharks.age.str.replace('Teen', '15')
sharks.age = sharks.age.str.replace('60s', '60')
sharks.age = sharks.age.str.replace('18 months', '0')
sharks.age = sharks.age.str.replace('50s', '50')
sharks.age = sharks.age.str.replace('teen', '15')
sharks.age = sharks.age.str.replace('28 & 26', '27')
sharks.age = sharks.age.str.replace('30s', '30')
sharks.age = sharks.age.str.replace('46 & 34', '40')
sharks.age = sharks.age.str.replace('15s', '15')
sharks.age = sharks.age.str.replace('\xa0 ', '-1')
sharks.age = sharks.age.str.replace('30 or 36', '33')
sharks.age = sharks.age.str.replace('6½', '6')
sharks.age = sharks.age.str.replace('21 & ?', '21')
sharks.age = sharks.age.str.replace('33 or 37', '35')
sharks.age = sharks.age.str.replace('mid-30', '35')
sharks.age = sharks.age.str.replace('12 or 13', '12')

In [46]:
sharks.age = sharks.age.str.replace(' ', '-1')

In [47]:
print(sharks['age'].unique())

['48' '-1' '18' '52' '15' '12' '32' '10' '21' '30' '60' '33' '29' '54'
 '34' '41' '37' '56' '19' '25' '69' '38' '35' '45' '14' '40' '28' '20'
 '24' '26' '22' '7' '31' '17' '13' '42' '50' '46' '82' '73' '68' '16' '39'
 '58' '55' '57' '47' '61' '65' '36' '43' '9' '49' '72' '59' '11' '27' '64'
 '23' '71' '44' '62' '6' '63' '70' '0' '53' '8' '51' '66' '77' '74' '3'
 '5' '86' '84' '21?' '75']

In [48]:
display(sharks[sharks['age'] == '21?'])

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
1925,2001.08.12,12-Aug-2001,2001.0,Unprovoked,thailand,Rayong Province,Laem Mae Pim Beach,Fell off banana boat,O. Jaimaung & friend,M,21?,Legs bitten,N,NaN,3 m [10'] shark,O. Jaimuang,2001.08.12-Jaimuang.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.08.12,2001.08.12,4378.0,Unknown,Unknown

In [49]:
sharks.loc[1925,'age'] = ['21']

In [50]:
print(sharks['age'].unique())

['48' '-1' '18' '52' '15' '12' '32' '10' '21' '30' '60' '33' '29' '54'
 '34' '41' '37' '56' '19' '25' '69' '38' '35' '45' '14' '40' '28' '20'
 '24' '26' '22' '7' '31' '17' '13' '42' '50' '46' '82' '73' '68' '16' '39'
 '58' '55' '57' '47' '61' '65' '36' '43' '9' '49' '72' '59' '11' '27' '64'
 '23' '71' '44' '62' '6' '63' '70' '0' '53' '8' '51' '66' '77' '74' '3'
 '5' '86' '84' '75']

In [51]:
display(sharks[sharks['injury'].isnull()])

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
1270,2008.04.20.a,20-Apr-2008,2008.0,Unprovoked,australia,New South Wales,Crescent Head,NaN,Jamie Adlington,M,-1,NaN,UNKNOWN,NaN,"Tiger shark, 2.3m","T. Peake, GSAF",2008.04.20.a-Adlington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.04.20.a,2008.04.20.a,5033.0,Unknown,Unknown

In [52]:
sharks[['injury']] = sharks[['injury']].fillna('Unknown')

In [53]:
display(sharks[sharks['investigatorOrSource'].isnull()])

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
119,2017.07.14.a,14-Jul-2017,2017.0,Unprovoked,australia,Western Australia,Floreat Beach,Surfing,male,M,-1,"Minor injury, grazed by shark",N,11h45,NaN,NaN,2017.07.14.a-Floreat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.14.a,2017.07.14.a,6184.0,Unknown,Unknown
290,2016.04.07.b,07-Apr-2016,2016.0,Unprovoked,usa,Florida,"Florida Keys, Monroe County",Fishing,Jonathan Lester,M,34,Left hand bitten,N,NaN,5' to 6' shark,NaN,2016.04.07.b-Lester.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.07.b,2016.04.07.b,6013.0,Unknown,Unknown
382,2015.07.27,27-Jul-2015,2015.0,Unprovoked,australia,Victoria,Tyrendarra Beach,Surfing,male,M,40,Injury to hand,NaN,NaN,NaN,NaN,2015.07.27-Victoria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.07.27,2015.07.27,5921.0,Unknown,Unknown
631,2013.08.31.b,31-Aug-2013,2013.0,Unprovoked,bahamas,NaN,Freetown Beach,Spearfishing,Bryan Collins,M,-1,Lower left leg bitten,N,NaN,Blacktip shark,NaN,2013.08.31.b-Collins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.08.31.b,2013.08.31.b,5672.0,Unknown,Unknown
1242,2008.06.28.a,28-Jun-2008,2008.0,Unprovoked,south africa,Western Cape Province,Mossel Bay,Surf skiing,Kobus Maritz,M,46,"No injury, ski bitten",N,14h00,"White shark, 2m",NaN,2008.06.28.a-Maritz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.06.28.a,2008.06.28.a,5061.0,Unknown,Unknown

In [54]:
sharks[['investigatorOrSource']] = sharks[['investigatorOrSource']].fillna('Unknown')

In [55]:
print(sharks['fatal(y/n)'].unique())

['N' 'Y' nan 'M' '2017' 'UNKNOWN']

In [56]:
display(sharks[sharks['fatal(y/n)'] == 'UNKNOWN'])

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
1270,2008.04.20.a,20-Apr-2008,2008.0,Unprovoked,australia,New South Wales,Crescent Head,NaN,Jamie Adlington,M,-1,Unknown,UNKNOWN,NaN,"Tiger shark, 2.3m","T. Peake, GSAF",2008.04.20.a-Adlington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.04.20.a,2008.04.20.a,5033.0,Unknown,Unknown

In [57]:
sharks.loc[1270,'fatal(y/n)'] = ['N']

In [58]:
display(sharks[sharks['fatal(y/n)'] == '2017'])

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
786,2012.06.10,10-Jun-2012,2012.0,Provoked,italy,Sardinia,Muravera,Attempting to rescue an injured & beached shark,Giorgio Zara,M,57,Lower left leg injured PROVOKED ACCIDENT,2017,Morning,"Blue shark, 2.5m","D. Puddo, 6/11/2012",2012.06.10-Zara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.10,2012.06.10,5517.0,Unknown,Unknown

In [59]:
sharks.loc[786,'fatal(y/n)'] = ['N']

In [60]:
display(sharks[sharks['fatal(y/n)'] == 'M'])

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
285,2016.04.18.b,18-Apr-2016,2016.0,Provoked,french polynesia,Tuamotos,Makemo Atoll,Spearfishing,Hoata Iotua,M,22,Laceration to knee by speared shark PROVOKED I...,M,Morning,"Grey reef shark, 2 m","TNTV News, 4/19/2016",2016.04.18.b-Iotua.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.04.18.b,2016.04.18.b,6018.0,Unknown,Unknown

In [61]:
sharks.loc[285,'fatal(y/n)'] = ['N']

In [62]:
fatalInjuries = (sharks[sharks['fatal(y/n)'].isnull()]) 
fatalInjuries.head(10)

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
27,2018.04.15.c,15-Apr-2018,2018.0,Unprovoked,brazil,Pernambuco,Piedade,Swimming,Pablo de Melo,M,34,"Multiple severe injuries to arms and leg, leg ...",NaN,NaN,NaN,"Globo, 4/16/2018",2018.04.15.c-deMelo.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.15.c,2018.04.15.c,6276.0,Unknown,Unknown
76,2017.10.01,01-Oct-2017,2017.0,Invalid,south africa,Western Cape Province,Dyer Island,Scuba Diving,Bradley Fick,M,31,FATAL,NaN,NaN,Death may have been due to drowning,"All Africa, 10/11/2017",2017.10.01-Fick.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.01,2017.10.01,6227.0,Unknown,Unknown
79,2017.09.24.b,24-Sep-2017,2017.0,Invalid,usa,New York,Rockaway,Surfing,Michah Behrend,M,33,"Lacerations to right ankle, foot & toe",NaN,15h30,Questionable,"S. Curatolo-Wageman, GSAF",2017.09.24.b-Behrend.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.24.b,2017.09.24.b,6224.0,Unknown,Unknown
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,south africa,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",NaN,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,Unknown,Unknown
107,2017.07.29.c,29-Jul-2017,2017.0,Invalid,usa,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Johnny Simatacolos,M,10,Abrasions and cuts to sole of foot,NaN,15h00,A small shark,"C. Creswell, GSAF",2017.07.29.c-Simatacolos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.07.29.c,2017.07.29.c,6196.0,Unknown,Unknown
125,2017.06.29,29-Jun-2017,2017.0,Invalid,usa,South Carolina,Wrightsville Beach,Fishing,male,M,-1,"Arm injured by hook, not by a shark",NaN,19h30,No shark invovlement,"C. Creswell, GSAF",2017.06.29-Wrightsville.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.29,2017.06.29,6178.0,Unknown,Unknown
153,2017.04.20,20-Apr-2017,2017.0,Invalid,usa,South Carolina,Georgetown County,Swimming,male,M,-1,Laceration & puncture wounds to left foot,NaN,08h50,Shark involvement not confirmed,"C. Creswell, GSAF",2017.04.20-PawleysIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.20,2017.04.20,6150.0,Unknown,Unknown
159,2017.04.12.a,12-Apr-2017,2017.0,Invalid,south africa,KwaZulu-Natal,Protea Banks,Scuba Diving,Leopold Mairhuber,M,68,"Fatal, coroner unable to determine if the dive...",NaN,NaN,Shark involvement prior to death not confirmed,"E. Ritter, GSAF",2017.04.12.a-Mairhuber.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.04.12.a,2017.04.12.a,6144.0,Unknown,Unknown
189,2017.01.03,03-Jan-2017,2017.0,Invalid,australia,New South Wales,Merimbula,Wading,Mitchell Collins,M,20,Minor injuries to foot & toes,NaN,18h00,Shark involvement not confirmed,"Illawarra Mercury, 1/7/2017",2017.01.03-Collins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.01.03,2017.01.03,6114.0,Unknown,Unknown
195,2016.12.11.a,11-Dec-2016,2016.0,Invalid,usa,Florida,"New Smyrna Beach, Volusia County",Surfing,Shane Garthwait,M,19,Cuts to right ankle & foot,NaN,Afternoon,Shark involvement not confirmed,"News Journal, 12/15/2016",2016.12.11.a-Garthwait.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.12.11.a,2016.12.11.a,6108.0,Unknown,Unknown

In [63]:
fatalInjuries.loc[76,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[84,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[159,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[437,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[525,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[437:570,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[660:688,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[763,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[874,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[890,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[967:1044,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1093,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1136:1212,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1240,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1272,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1301,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1381:1407,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1433:1499,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1563,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1606,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1696,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1799,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1866:1879,'fatal(y/n)'] = 'Y'
fatalInjuries.loc[1941:1947,'fatal(y/n)'] = 'Y'

In [64]:
fatalInjuries[['fatal(y/n)']] = fatalInjuries[['fatal(y/n)']].fillna('N') # los que no han sido mortales lo indicamos con N

In [65]:
mortalAttacksIndex = fatalInjuries[fatalInjuries['fatal(y/n)'] == 'Y' ].index
notMortalAttacksIndex = fatalInjuries[fatalInjuries['fatal(y/n)'] == 'N' ].index # con esto hayamos los indices de Y y N de fatalInjuries

In [66]:
sharks.loc[mortalAttacksIndex, 'fatal(y/n)'] = 'Y'
sharks.loc[notMortalAttacksIndex, 'fatal(y/n)'] = 'N' # sustituimos en el dataframe original los nulos de fatal con lo hallado previamente

In [67]:
print(sharks['fatal(y/n)'].unique())

['N' 'Y']

In [68]:
print(sharks['caseNumber'].unique())

['2018.06.09' '2018.06.08' '2018.06.04' ... '2001.01.24.R' '2001.01.09'
 '2001.01.06']

In [69]:
sharks.head(70)

,caseNumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal(y/n),time,species,investigatorOrSource,pdf,hrefFormula,href,caseNumber1,caseNumber2,originalOrder,unnamed22,unnamed23
2,2018.06.09,09-Jun-2018,2018.0,Invalid,usa,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,Unknown,Unknown
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,australia,New South Wales,Arrawarra Headland,Surfing,male,M,-1,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,Unknown,Unknown
4,2018.06.04,04-Jun-2018,2018.0,Provoked,mexico,Colima,La Ticla,Free diving,Gustavo Ramos,M,-1,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,Unknown,Unknown
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,australia,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris,M,-1,"No injury, board bitten",N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0,Unknown,Unknown
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,brazil,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,FATAL,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,2017.09.20,20-Sep-2017,2017.0,Unprovoked,usa,Florida,Palm Beach County,Surfing,Richard Inniss,M,-1,Minor lacerations to sole of left foot,N,Morning,NaN,"WPTV, 9/25/2017",2017.09.20-Inniss.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.20,2017.09.20,6222.0,Unknown,Unknown
82,2017.09.16.b,16-Sep-2017,2017.0,Unprovoked,spain,Canary Islands,Gran Canaria,Body surfing,male,M,13,Lacerations to right foot,N,NaN,"Porbeagle, 1.5 m",Turismo La Aldea,2017.09.16.b-GrandCanary.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.16.b,2017.09.16.b,6221.0,Unknown,Unknown
83,2017.09.16.a,16-Sep-2017,2017.0,Unprovoked,usa,Florida,"Ponce Inlet, Volusia County",Surfing,male,M,28,Lacerations to left foot,N,16h30,NaN,"Orlando Sentinel, 9/16/2017",2017.09.16.a-Volusia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.16.a,2017.09.16.a,6220.0,Unknown,Unknown
84,2017.09.15.b,15-Sep-2017,2017.0,Invalid,south africa,Western Cape Province,Hawston,Scuba Diving,Wayon Love,M,25,"FATAL, but death was probably due to drowning",Y,Afternoon,NaN,"Ground Up, 9/20/2017",2017.09.15.b-Love.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.b,2017.09.15.b,6219.0,Unknown,Unknown
85,2017.09.15.a,15-Sep-2017,2017.0,Unprovoked,samoa,Upolu Island,Nofoalii,Fishing,male,M,-1,Injuries to hands and legs,N,Night,NaN,"Samoa Observer, 9/16/2017",2017.09.15.a-Samoa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.15.a,2017.09.15.a,6218.0,Unknown,Unknown

In [70]:
for i,row in sharks.iterrows():
    print(i, row['caseNumber'])

2 2018.06.09
3 2018.06.08
4 2018.06.04
5 2018.06.03.b
6 2018.06.03.a
7 2018.05.27
8 2018.05.26.b
9 2018.05.26.a
10 2018.05.24
11 2018.05.21
12 2018.05.13.b
13 2018.05.13.a
15 2018.05.12
16 2018.05.09
17 2018.04.30.R
18 2018.04.28.b
19 2018.04.28.a
20 2018.04.25.b
21 2018.04.25.a
22 2018.04.24
23 2018.04.23
24 2018.04.22
25 2018.04.19
26 2018.04.15.d
27 2018.04.15.c
28 2018.04.15.b
29 2018.04.15.a
30 2018.04.14
31 2018.04.10.R
33 2018.04.05
34 2018.04.03
35 2018.03.31
36 2018.03.14
37 2018.03.09.b
38 2018.03.09.a
39 2018.02.24
41 2018.02.17
42 2018.02.15
45 2018.02.03
46 2018.02.01
47 2018.01.28
48 2018.01.21
49 2018.01.14
50 2018.01.13
51 2018.01.12
52 2018.01.05
55 2017.12.21
57 2017.11.30.b
60 2017.11.24
62 2017.11.13.R
63 2017.11.13
64 2017.11.04
65 2017.10.31.R
66 2017.10.28
67 2017.10.26
68 2017.10.23.c
69 2017.10.23.b
72 2017.10.21
73 2017.10.18
74 2017.10.09
76 2017.10.01
77 2017.09.25.b
78 2017.09.25.a
79 2017.09.24.b
80 2017.09.24.a
81 2017.09.20
82 2017.09.16.b
83 2017.09.16.a
84 2017.09.15.b
85 2017.09.15.a
87 2017.09.13
88 2017.09.10.b
89 2017.09.10.a
90 2017.09.06.R
91 2017.09.03.b
92 2017.09.03.a
93 2017.09.02.c
95 2017.09.02.a
96 2017.08.29
99 2017.08.26.a
100 2017.08.23
101 2017.08.18
102 2017.08.10
104 2017.08.03
105 2017.08.01
106 2017.07.31
107 2017.07.29.c
110 2017.07.26.R
111 2017.07.24
116 2017.07.20.b
117 2017.07.20.a
118 2017.07.14.b
119 2017.07.14.a
120 2017.07.11
121 2017.07.09
122 2017.07.07.R
125 2017.06.29
127 2017.06.19
129 2017.06.18.a
130 2017.06.17
131 2017.06.05
133 2017.06.11
135 2017.06.10.a
136 2017.06.07.R
137 2017.06.04
140 2017.05.28
141 2017.05.27
142 2017.05.12
143 2017.05.06.R
144 2017.05.06
147 2017.04.29.c
149 2017.04.29.a
153 2017.04.20
156 2017.04.14
157 2017.04.13
159 2017.04.12.a
163 2017.04.06
165 2017.04.02.b
167 2017.03.27
168 2017.03.19
169 2017.03.18
170 2017.03.11
171 2017.03.09
173 2017.02.24
174 2017.02.21
175 2017.02.17
176 2017.02.11
178 2017.02.06.a
180 2017.02.01.a
181 2017.01.24
182 2017.01.22
183 2017.01.21
184 2017.01.13.b
185 2017.01.13.a
186 2017.01.09
188 2017.01.05
189 2017.01.03
190 2016.12.27
192 2016.12.19
193 2016.12.14
194 2016.12.11.b
195 2016.12.11.a
196 2016.12.06
197 2016.12.01
198 2016.11.28
200 2016.10.30
201 2016.10.29
202 2016.10.24
203 2016.10.21
204 2016.10.15
206 2016.10.13.R
207 2016.10.12
208 2016.10.10
209 2016.10.02
210 2016.10.01
211 2016.09.26
212 2016.09.18.c
213 2016.09.18.b
214 2016.09.18.a
215 2016.09.17.b
216 2016.09.17.a
217 2016.09.15
219 2016.09.11
221 2016.09.06
223 2016.09.05.a
224 2016.09.04
225 2016.09.01
227 2016.08.29.b
228 2016.08.29.a
229 2016.08.27
230 2016.08.25
231 2016.08.07
232 2016.08.06
233 2016.08.04
234 2016.07.29
235 2016.07.28.R
236 2016.07.28
237 2016.07.27
238 2016.07.26
239 2016.07.24
240 2016.07.23.b
241 2016.07.23.a
242 2016.07.20
246 2016.07.15.b
247 2016.07.15.a
248 2016.07.14.R
250 2016.07.08
251 2016.07.07.b
252 2016.07.07.a
254 2016.07.04
255 2016.06.27
256 2016.06.25
257 2016.06.24
258 2016.06.23
259 2016.06.21.b
260 2016.06.21.a
261 2016.06.15.b
262 2016.06.15.a
264 2016.06.11
265 2016.06.07
266 2016.06.05.b
268 2016.06.04
269 2016.06.02.b
270 2016.06.02.a
271 2016.05.31
273 2016.05.29.a
277 2016.05.18
279 2016.05.03
280 2016.05.02
281 2016.04.25
282 2016.04.23
283 2016.04.22
284 2016.04.19
285 2016.04.18.b
286 2016.04.18.a
287 2016.04.13
289 2016.04.08
290 2016.04.07.b
291 2016.04.07.a
293 2016.03.30
294 2016.03.28.b
295 2016.03.28.a
296 2016.03.26
298 2016.03.11
299 2016.03.10
300 2016.03.04
301 2016.03.03.R
302 2016.03.02
303 2016.02.22
304 2016.02.19
306 2016.02.10.R
307 2016.02.10
309 2016.02.04
310 2016.02.02
311 2016.01.29
312 2016.01.28
314 2016.01.24.b
315 2016.01.24.a
316 2016.01.23
317 2016.01.11.R
318 2016.01.05
319 2016.01.02
320 2015.12.26
322 2015.12.22
323 2015.12.21.b
324 2015.12.21.a
325 2015.12.19
327 2015.12.11
329 2015.11.20
330 2015.11.16
332 2015.11.15.a
333 2015.11.10
335 2015.11.03
337 2015.11.01.a
338 2015.10.30
339 2015.10.28.a
340 2015.10.25
341 2015.10.21
342 2015.10.19
344 2015.10.17.b
345 2015.10.17.a
346 2015.10.13
348 2015.10.09.a
349 2015.10.08
350 2015.10.07
351 2015.10.05.b
352 2015.10.05.a
353 2015.10.04
354 2015.09.29
356 2015.09.24
357 2015.09.20.d
358 2015.09.20.c
359 2015.09.20.b
360 2015.09.20.a
361 2015.09.19
362 2015.09.18
363 2015.09.17
364 2015.09.08
366 2015.09.05
367 2015.09.04
368 2015.09.03
370 2015.09.00
372 2015.08.29.a
373 2015.08.22.b
374 2015.08.22.a
375 2015.08.20
377 2015.08.18.b
378 2015.08.18.a
379 2015.08.10
380 2015.07.31
381 2015.07.28
382 2015.07.27
383 2015.07.26.b
385 2015.07.25
386 2015.07.23.b
387 2015.07.23.a
388 2015.07.22
389 2015.07.19
390 2015.07-10
391 2015.07.08
392 2015.07.06
394 2015.07.04.a
395 2015.07.03
396 2015.07.02
397 2015.07.01
398 2015.06.30.b
399 2015.06.30.a
400 2015.06.27.b
401 2015.06.27.a
403 2015.06.26.b
404 2015.06.26.a
405 2015.06.25.R
406 2015.06.25
407 2015.06.24.b
409 2015.06.23
410 2015.06.19
411 2015.06.17
412 2015.06.14.b
416 2015.06.07
418 2015.06.01
421 2015.05.25
423 2015.05.20
424 2015.05.15
425 2015.05.09
426 2015.05.07
427 2015.05.03
428 2015.05.02
430 2015.04.26
431 2015.04.25
432 2015.04.24.c
433 2015.04.13
434 2015.04.12
435 2015.04.11
436 2015.04.03
437 2015.03.29
438 2015.03.31
439 2015.03.26
440 2015.03.21
441 2015.03.18
442 2015.03.16
443 2015.03.11
444 2015.03.10
445 2015.03.07
448 2015.02.09
449 2015.02.08
450 2015.02.05
451 2015.01.30
452 2015.01.27
453 2015.01.24
454 2015.01.23
455 2015.01.19.b
457 2015.01.17
458 2015.01.16
459 2015.01.08
461 2015.01.03
462 2015.01.01
464 2014.12.29.a
467 2014.12.28.b
468 2014.12.28.a
469 2014.12.23.R
470 2014.12.15
471 2014.12.03.R
472 2014.11.29
473 2014.11.20
474 2014.11.19
476 2014.11.16
477 2014.11.13
478 2014.11.10
479 2014.11.08
481 2014.10.30
483 2014.10.20
485 2014.10.18
489 2014.10.11
490 2014.10.05.b
492 2014.10.05.a
493 2014.10.03.b
494 2014.10.03.a
495 2014.10.02.b
496 2014.10.02.a
497 2014.09.21
499 2014.09.13
500 2014.09.09
501 2014.09.06
503 2014.09.02
504 2014.09.00
506 2014.08.29.b
508 2014.08.28
510 2014.08.27.b
512 2014.08.25
514 2014.08.16
515 2014.08.12
516 2014.08.10
517 2014.08.09.R
519 2014.08.08
520 2014.08.06
522 2014.08.02
523 2014.08.02
524 2014.08.01
525 2014.08.00
526 2014.07.27
527 2014.07.22
528 2014.07.21
530 2014.07.16
531 2014.07.14
532 2014.07.13
533 2014.07.12
534 2014.07.09
535 2014.07.05.b
536 2014.07.05.a
537 2014.07.03
538 2014.06.27.R
539 2014.06.25
540 2014.06.18.b
541 2014.06.18.a
542 2014.06.17.R
543 2014.06.09.c
544 2014.06.09.b
545 2014.06.09.a
546 2014.06.08
549 2014.06.01.b
552 2014.05.23
553 2014.05.22
555 2014.05.14
557 2014.05.11
558 2014.05.10.R
561 2014.05.01
562 2014.04.24
563 2014.04.22
564 2014.04.15
566 2014.04.12
567 2014.04.04.b
568 2014.04.04.a
570 2014.03.29
571 2014.03.22.b
572 2014.03.22.a
573 2014.03.21
574 2014.03.18.c
575 2014.03.18.b
577 2014.03.12
578 2014.03.13
579 2014.03.02
580 2014.02.20
581 2014.02.17
582 2014.02.08
583 2014.02.07.b
584 2014.02.07
585 2014.01.26
586 2014.01.25
587 2014.01.04
588 2014.00.00.b
590 2013.12.25
591 2013.12.16
592 2013.12.13
593 2013.12.11
594 2013.12.10
595 2013.12.05
596 2013.12.02
597 2013.11.30
599 2013.11.23.a
600 2013.11.22
601 2013.11.12
602 2013.11.10
603 2013.11.07.b
604 2013.11.07.a
605 2013.10.31
607 2013.10.26.b
608 2013.10.26.a
609 2013.10.24
610 2013.10.23
611 2013.10.20
612 2013.10.19
613 2013.10.11
614 2013.10.08
615 2013.10.05
616 2013.10.05
617 2013.09.29.b
618 2013.09.29.a
619 2013.09.25
620 2013.09.21.b
621 2013.09.21.a
622 2013.09.14
625 2013.09.07.b
626 2013.09.07.a
627 2013.09.02
628 2013.09.01.c
629 2013.09.01.b
630 2013.09.01.a
631 2013.08.31.b
632 2013.08.31.a
634 2013.08.26
636 2013.08.25
637 2013.08.18
641 2013.08.11
642 2013.08.08.R
643 2013.08.05
645 2013.07.30
646 2013.07.29.c
648 2013.07.29.a
649 2013.07.28.b
650 2013.07.28.a
653 2013.07.17.R
655 2013.07.14
657 2013.07.09
658 2013.07.02
659 2013.06.30
660 2013.06.27
661 2013.06.25.c
662 2013.06.25.b
663 2013.06.25.a
664 2013.06.18
665 2013.06.17
666 2013.06.16
669 2013.06.06.b
670 2013.06.06.a
671 2013.05.27.b
672 2013.05.27.a
673 2013.05.23.b
674 2013.05.23.a
675 2013.05.14
676 2013.05.08.b
677 2013.05.08.a
678 2013.05.04.a
679 2013.04.28
681 2013.04.21
682 2013.04.17
683 2013.04.14
684 2013.04.13.b
685 2013.04.13.a
686 2013.04.10
687 2013.04.04
688 2013.04.02.R
689 2013.04.02.a
690 2013.03.31
691 2013.03.29
693 2013.03.21
694 2013.03.16.b
695 2013.03.16.a
696 2013.03.12
697 2013.03.10.b
698 2013.03.10.a
699 2013.03.03
700 2013.02.27
702 2013.02.21.a
703 2013.02.10
704 2013.02.09
705 2013.02.01
706 2013.01.26
707 2013.01.25
708 2013.01.21.R
709 2013.01.16
710 2013.01.13
711 2013.01.05
712 2012.12.31
713 2012.12.30
714 2012.12.28
715 2012.12.25
716 2012.12.19
717 2012.12.05
718 2012.12.02
720 2012.11.30
721 2012.11.27
722 2012.11.22
723 2012.11.19
724 2012.11.04.b
725 2012.11.04.a
726 2012.10.30
728 2012.10.23
730 2012.10.18.b
731 2012.10.18.a
732 2012.10.16
734 2012.10.07
735 2012.10.02
736 2012.09.25
737 2012.09.24
738 2012.09.16
741 2012.09.08.b
742 2012.09.08.a
743 2012.09.06.b
744 2012.09.06.a
745 2012.09.04
749 2012.08.31
750 2012.08.28
751 2012.08.26
752 2012.08.15
754 2012.08.09
755 2012.08.05
756 2012.08.04
757 2012.07.31.b
758 2012.07.31.a
759 2012.07.30.b
760 2012.07.30.a
761 2012.07.24
762 2012.07.23
763 2012.07.21
765 2012.07.14
767 2012.07.07.c
769 2012.07.07.a
770 2012.07.06
772 2012.06.26.c
773 2012.06.26.b
775 2012.06.22.b
776 2012.06.22.a
777 2012.06.20
778 2012.06.19
780 2012.06.15
782 2012.06.14.c
783 2012.06.14.b
784 2012.06.14.a
785 2012.06.12
786 2012.06.10
787 2012.06.03
789 2012.06.02.a
791 2012.05.29
792 2012.05.23
793 2012.05.20
794 2012.05.16
795 2012.05.12
798 2012.04.19.b
799 2012.04.19.a
800 2012.04.11
801 2012.04.03
802 2012.04.00
803 2012.03.31
804 2012.03.24
806 2012.03.20
807 2012.03.15
809 2012.03.14.a
810 2012.03.06.b
812 2012.03.05
813 2012.03.04
814 2012.03.03
815 2012.03.01
816 2012.02.26
817 2012.02.25
819 2012.02.06
821 2012.01.19
822 2012.01.22.R
823 2012.01.18.b
824 2012.01.18.a
825 2012.01.15
826 2012.01.13
827 2012.01.03
828 2012.01.02
829 2011.12.31
830 2011.12.26.R
831 2011.12.25
832 2011.12.23
833 2011.12.21.b
834 2011.12.21.a
835 2011.12.11
836 2011.12.07.b
837 2011.12.07.a
840 2011.12.02
841 2011.11.29
842 2011.11.28
843 2011.11.22
844 2011.11.20.R
845 2011.11.12
846 2011.11.11
847 2011.10.29.
848 2011.10.28.R
850 2011.10.22
851 2011.10.20
852 2011.10.19
853 2011.10.11
854 2011.10.10
855 2011.10.09
856 2011.10.05
857 2011.10.02
858 2011.10.01
859 2011.09.30
860 2011.09.28.b
861 2011.09.28.a
862 2011.09.24.b
863 2011.09.24.a
864 2011.09.20
865 2011.09.19
866 2011.09.17
867 2011.09.16
868 2011.09.11.b
869 2011.09.11.a
871 2011.09.04.a
872 2011.09.02
873 2011.08.31
874 2011.08.28.b
876 2011.08.26
877 2011.08.24.b
878 2011.08.24.a
879 2011.08.23
880 2011.08.18
882 2011.08.17.b.
883 2011.08.17.a
884 2011.08.16.c
885 2011.08.16.b
886 2011.08.16.a
887 2011.08.15
888 2011.08.11
889 2011.08.01
890 2011.07.31
891 2011.07.30
892 2011.07.25
893 2011.07.22
895 2011.07.15
896 2011.07.13.b
897 2011.07.13.a
898 2011.07.07.b
899 2011.07.07.a
900 2011.07.06
901 2011.07.05
902 2011.06.30
903 2011.06.29
904 2011.06.28
906 2011.06.24
907 2011.06.21
908 2011.06.19.b
909 2011.06.19.a
910 2011.06.15
912 2011.06.12
913 2011.06.06.R
914 2011.06.06.b
915 2011.06.06.a
918 2011.05.29
921 2011.05.21.b
922 2011.05.13.b
923 2011.05.21.a
924 2011.05.13.a
925 2011.05.10
926 2011.05.07.R
927 2011.05.04
928 2011.04.26
929 2011.04.23
930 2011.04.22
931 2011.04.16
932 2011.04.12
933 2011.04.08
934 2011.03.29.R
936 2011.03.23
937 2011.03.21.b
938 2011.03.21.a
941 2011.03.10
942 2011.02.28.R
943 2011.02.23
944 2011.02.19
945 2011.02.17
946 2011.02.13
947 2011.02.12
948 2011.02.04.R
949 2011.02.02
951 2011.01.28
952 2011.01.26
954 2011.01.15
955 2011.01.12.R
957 2010.12.26
958 2010.12.17

959 2010.12.11
961 2010.12.03.R
962 2010.12.01.b
963 2010.12.01.a
966 2010.11.27.R
967 2010.11.27
968 2010.11.19
969 2010.11.15
970 2010.11.14
971 2010.11.12.R
973 2010.10.28.R
974 2010.10.28
975 2010.10.25
976 2010.10.23.b
977 2010.10.23.a
978 2010.10.22
980 2010.10.09
981 2010.10.02.b
983 2010.10.01
984 2010.09.27
985 2010.09.24
986 2010.09.21
987 2010.09.13
988 2010.09.07
989 2010.09.06.R
990 2010.09.04
991 2010.09.03.b
992 2010.09.03.a
993 2010.09.02
994 2010.08.29
995 2010.08.18
996 2010.08.17
997 2010.08.14
1000 2010.08.08
1001 2010.08.07.b
1002 2010.08.07.a
1004 2010.08.02.b
1006 2010.07.25
1007 2010.07.23
1008 2010.07.19
1010 2010.07.17.a
1011 2010.07.16.b
1012 2010.07.16.a
1013 2010.07.11
1015 2010.07.03
1016 2010.07.02.b
1017 2010.07.02.a
1018 2010.06.27
1021 2010.06.15
1023 2010.06.06
1024 2010.06.00
1025 2010.05.30
1028 2010.05.18.a
1029 2010.05.03
1031 2010.04.28
1032 2010.04.19
1033 2010.04.13
1034 2010.04.04
1035 2010.03.27
1036 2010.02.19
1037 2010.02.16
1038 2010.02.15
1040 2010.02.11
1041 2010.02.06.R
1042 2010.02.06.b
1043 2010.02.06.a
1044 2010.02.04
1045 2010.02.03
1047 2010.01.30
1048 2010.01.27
1049 2010.01.22.b
1050 2010.01.22.a
1051 2010.01.12
1054 2010.01.09.b
1055 2010.01.09.a
1056 2010.01.06
1057 2010.01.05
1058 2009.12.29
1059 2009.12.26
1060 2009.12.22
1061 2009.12.20.b
1062 2009.12.20.a
1063 2009.12.18
1064 2009.12.18
1065 2009.12.16
1066 2009.12.13
1068 2009.12.06
1069 2009.11.25
1070 2009.11.24
1071 2009.11.16.b
1072 2009.11.16.a
1074 2009.11.11
1075 2009.11.08
1076 2009.11.05
1077 2009.10.30
1078 2009.10.29.R
1080 2009.10.24
1081 2009.10.19
1083 2009.10.17
1084 2009.10.14.R
1085 2009.10.09
1086 2009.10.02
1087 2009.09.26
1088 2009.09.18
1089 2009.09.15
1090 2009.09.13
1091 2009.09.12
1092 2009.09.07
1093 2009.09.02
1094 2009.09.01
1095 2009.08.30
1096 2009.08.29
1098 2009.08.11
1099 2009.08.10
1100 2009.08.06
1101 2009.08.01
1102 2009.07.31
1103 2009.07.30
1105 2009.07.24.R
1110 2009.07.18
1111 2009.07.11.b
1112 2009.07.11.a
1113 2009.07.07
1116 2009.06.27
1117 2009.06.21
1118 2009.06.16
1119 2009.06.14.R
1120 2009.06.02.b
1121 2009.06.02.a
1123 2009.05.31
1124 2009.05.25
1125 2009.05.17
1126 2009.05.16.b
1127 2009.05.16.a
1128 2009.05.12
1129 2009.05.06
1131 2009.04.25.R
1132 2009.04.21
1133 2009.04.20
1134 2009.04.19
1135 2009.04.17.
1136 2009.04.11
1137 2009.04.12
1138 2009.04.06.b
1139 2009.04.06.a
1140 2009.04.03
1141 2009.03.27
1142 2009.03.21
1143 2009.03.20
1144 2009.03.19.b
1148 2009.03.17
1149 2009.03.16.R
1150 2009.03.06
1151 2009.03.02
1152 2009.03.01.b
1153 2009.03.01.a
1154 2009.02.22
1155 2009.02.18
1156 2009.02.12
1157 2009.02.11
1158 2009.02.08
1159 2009.02.07.b
1160 2009.02.07.a
1161 2009.01.27.R
1162 2009.01.26.R
1163 2009.01.25
1165 2009.01.24.b
1166 2009.01.24.a
1167 2009.01.23
1168 2009.01.18
1169 2009.01.16
1171 2009.01.12
1173 2009.01.11.a
1175 2009.01.10.a
1176 2009.01.06
1180 2008.12.27.c
1181 2008.12.27.b
1182 2008.12.27.a
1183 2008.12.20
1184 2008.12.14
1185 2008.12.10
1187 2008.12.00
1189 2008.11.25
1191 2008.11.09.b
1192 2008.11.09.a
1193 2008.11.06
1194 2008.10.22
1195 2008.10.21
1196 2008.10.12
1197 2008.10.11
1198 2008.10.08
1199 2008.10.06
1200 2008.09.28.b
1201 2008.09.28.a
1202 2008.09.15
1203 2008.09.14
1204 2008.09.09
1205 2008.09.08
1206 2008.09.07
1207 2008.09.06.b
1208 2008.09.06.a
1209 2008.09.01
1210 2008.09.00
1211 2008.08.30.c
1212 2008.08.30.b
1213 2008.08.30.a
1214 2008.08.28
1215 2008.08.27
1216 2008.08.24
1218 2008.08.20
1219 2008.08.18
1222 2008.08.11
1223 2008.07.30.R
1224 2008.07.30
1225 2008.07.27
1226 2008.07.26.b
1227 2008.07.26.a
1228 2008.07.25.b
1230 2008.07.24.b
1232 2008.07.23
1233 2008.07.19
1234 2008.07.18
1235 2008.07.13
1236 2008.07.11
1239 2008.07.00
1240 2008.06.28.c
1241 2008.06.28.b
1242 2008.06.28.a
1243 2008.06.26.R
1244 2008.06.26.b
1245 2008.06.26.a
1246 2008.06.24
1249 2008.06.11
1250 2008.06.07
1253 2008.06.01.a
1254 2008.05.26
1255 2008.05.24.b
1256 2008.05.24.a
1257 2008.05.23
1258 2008.05.14
1259 2008.05.10
1260 2008.05.07.b
1261 2008.05.07.a
1262 2008.05.01
1263 2008.04.28.b
1264 2008.04.28.a
1265 2008.04.27
1266 2008.04.26.b
1267 2008.04.26.a
1268 2008.04.25
1269 2008.04.20.b
1270 2008.04.20.a
1271 2008.04.19.R
1272 2008.04.18
1273 2008.04.17
1274 2008.04.15
1275 2008.04.09.R
1276 2008.03.25
1278 2008.04.08
1279 2008.04.03
1280 2008.03.28.c
1281 2008.03.28.b
1282 2008.03.28.a
1283 2008.03.23
1284 2008.03.21
1285 2008.03.15
1286 2008.03.07
1287 2008.02.24
1288 2008.02.21.R
1289 2008.02.15
1291 2008.02.06
1292 2008.01.30
1293 2008.01.29
1294 2008.01.27
1295 2008.01.19.R
1297 2008.01.10
1298 2008.00.00.b
1299 2008.00.00.a
1300 2007.12.21
1301 2007.12.19
1302 2007.12.18
1303 2007.12.15
1304 2007.12.14
1305 2007.12.10
1307 2007.12.07
1308 2007.11.18
1309 2007.11.08
1310 2007.11.07
1311 2007.11.06
1312 2007.11.04
1313 2007.11.03
1314 2007.11.00
1315 2007.10.29
1317 2007.10.13
1318 2007.10.07
1319 2007.10.06
1320 2007.09.30.c
1321 2007.09.30.b
1328 2007.09.20
1329 2007.09.17
1330 2007.09.16.b
1332 2007.09.13
1335 2007.09.04
1337 2007.09.03.a
1338 2007.08.28.b
1339 2007.08.28.a
1340 2007.08.26
1341 2007.08.25
1342 2007.08.22
1343 2007.08.20
1344 2007.08.19.c
1345 2007.08.19.b
1346 2007.08.19.a.
1347 2007.08.15
1349 2007.08.11
1350 2007.08.09.b
1351 2007.08.09.a
1353 2007.07.29
1354 2007.07.28
1355 2007.07.22
1356 2007.07.21
1357 2007.07.19.b
1358 2007.07.19.a
1359 2007.07.18.b
1360 2007.07.18.a
1364 2007.07.05
1365 2007.07.04
1367 2007.06.30.b
1369 2007.06.25
1370 2007.06.24
1373 2007.06.05
1376 2007.05.17.R
1378 2007.05.12
1380 2007.05.09.R
1381 2007.05.08
1383 2007.05.07.a
1387 2007.04.22
1388 2007.04.20
1390 2007.04.09
1391 2007.04.01
1392 2007.03.31.b
1393 2007.03.31.a
1395 2007.03.21
1397 2007.03.14.R
1399 2007.03.11
1400 2007.03.05.R
1401 2007.02.04
1402 2007.02.03
1403 2007.02.00
1404 2007.01.25.b
1406 2007.01.23
1407 2007.01.19
1408 2007.01.14
1409 2007.01.09
1410 2007.01.07
1411 2007.01.05
1412 2006.12.18
1413 2006.12.11
1414 2006.12.10
1415 2006.12.06
1416 2006.12.02
1418 2006.11.11
1419 2006.11.09
1420 2006.10.31
1421 2006.10.16
1422 2006.10.10
1423 2006.10.07
1424 2006.10.05
1427 2006.09.30
1428 2006.09.29
1429 2006.09.18.R
1430 2006.09.16
1431 2006.09.14
1432 2006.09.11
1433 2006.09.04
1434 2006.09.03.b
1435 2006.09.03.a
1436 2006.09.02
1437 2006.09.02
1438 2006.08.29.b
1439 2006.08.29.a
1440 2006.08.27
1441 2006.08.22.b
1442 2006.08.22.a
1443 2006.08.20.b
1444 2006.08.20.a
1445 2006.08.15
1446 2006.08.13
1448 2006.08.00.a
1450 2006.07.31.a
1451 2006.07.29.b
1452 2006.07.29.a
1453 2006.07.28
1454 2006.07.25
1455 2006.07.23
1457 2006.07.17
1460 2006.07.10
1461 2006.07.09.b
1462 2006.07.09.a
1464 2006.07.08.a
1466 2006.06.30.a
1468 2006.06.26
1469 2006.06.24
1471 2006.06.18
1472 2006.06.17
1473 2006.06.15
1475 2006.06.05
1476 2006.05.31
1478 2006.05.27
1479 2006.05.24
1480 2006.05.21
1482 2006.05.10
1484 2006.05.02
1485 2006.04.23.R
1486 2006.04.21
1488 2006.04.13
1489 2006.04.11
1490 2006.04.09.b
1491 2006.04.09.a
1492 2006.04.03
1493 2006.03.28.R
1495 2006.03.22
1496 2006.03.19
1497 2006.03.15
1499 2006.02.23
1500 2006.02.13
1501 2006.02.12.b
1502 2006.02.12.a
1503 2006.02.08
1505 2006.02.01.a
1506 2006.01.28.R
1507 2006.01.25
1509 2006.01.18
1510 2006.01.15
1511 2006.01.11
1513 2006.01.04
1514 2006.01.01
1515 2005.12.24
1516 2005.12.21
1518 2005.12.11
1520 2005.11.29.R
1521 2005.11.27
1523 2005.11.25.b
1524 2005.11.25.a
1526 2005.11.21
1527 2005.11.20
1529 2005.11.15
1530 2005.11.12
1531 2005.11.02.b
1532 2005.11.02.a
1533 2005.10.29
1534 2005.10.25
1535 2005.10.22
1536 2005.10.21
1538 2005.10.15
1539 2005.10.13
1541 2005.10.06
1542 2005.10.03
1543 2005.10.01
1544 2005.09.27.R
1545 2005.09.24
1546 2005.09.23
1547 2005.09.22
1549 2005.09.11
1550 2005.09.07
1552 2005.09.04.a
1553 2005.09.02.b
1554 2005.09.02.a
1555 2005.08.24.b
1556 2005.08.24.a
1557 2005.08.22
1558 2005.08.21
1559 2005.08.19
1561 2005.08.12
1562 2005.08.06
1563 2005.08.01
1565 2005.07.23
1566 2005.07.22
1567 2005.07.17.b
1568 2005.07.17.a
1570 2005.07.15
1572 2005.07.01
1573 2005.06.27
1576 2005.06.21
1577 2005.06.18
1578 2005.06.16
1581 2005.06.05
1582 2005.06.04
1583 2005.06.02
1584 2005.05.28
1586 2005.05.25
1587 2005.05.15
1589 2005.05.03
1590 2005.05.02.R
1591 2005.05.02
1592 2005.04.25
1594 2005.04.16.b
1595 2005.04.16.a
1597 2005.04.09
1598 2005.04.07

1601 2005.03.28
1602 2005.03.27.R
1603 2005.03.25
1604 2005.03.19
1605 2005.03.12
1606 2005.03.10
1607 2005.03.09
1608 2005.03.05
1609 2005.02.26
1610 2005.02.22
1611 2005.02.16
1612 2005.02.13
1613 2005.02.04
1614 2005.01.20
1615 2005.01.19
1617 2005.01.08
1619 2004.12.16
1620 2004.12.11
1621 2004.11.27
1622 2004.11.26
1625 2004.11.11.a
1627 2004.10.31
1629 2004.10.30.a
1630 2004.10.21
1631 2004.10.10
1632 2004.10.09.b
1633 2004.10.09.a
1634 2004.10.06
1635 2004.10.02
1636 2004.10.01
1638 2004.09.20
1639 2004.09.10
1643 2004.08.21
1644 2004.08.20
1645 2004.08.15
1646 2004.08.06
1647 2004.08.03
1650 2004.07.30
1654 2004.07.25
1656 2004.07.15
1657 2004.07.10
1659 2004.07.02.a
1660 2004.06.26.b
1661 2004.06.26.a
1663 2004.06.10.b
1664 2004.06.10.a
1665 2004.06.02
1666 2004.05.29
1667 2004.05.23.b
1668 2004.05.28
1669 2004.05.23.a
1670 2004.05.22.c
1673 2004.05.18
1674 2004.05.04
1675 2004.05.01
1676 2004.04.26
1678 2004.04.13.b
1679 2004.04.13.a
1680 2004.04.07
1681 2004.04.05
1683 2004.03.31.b
1684 2004.03.31.a
1685 2004.03.29
1686 2004.03.28
1687 2004.03.27.b
1688 2004.03.27.a
1690 2004.03.22
1691 2004.03.16
1692 2004.03.06
1693 2004.02.29
1694 2004.02.26
1695 2004.02.21
1696 2004.02.16
1697 2004.02.14
1698 2004.02.11
1699 2004.01.25
1700 2004.01.23
1701 2004.01.22
1702 2004.01.21.b
1703 2004.01.21.a
1704 2004.01.15.R
1705 2004.01.12
1706 2004.01.07
1707 2004.01.03.b
1709 2004.00.00
1711 2003.12.26
1712 2003.12.13.b
1713 2003.12.13.a
1714 2003.12.08
1715 2003.11.30.b
1716 2003.11.30.a
1717 2003.11.27
1719 2003.11.12.b
1720 2003.11.12.a
1721 2003.11.06.b
1723 2003.11.01
1724 2003.11.00
1725 2003.10.31.c
1726 2003.10.31.b
1728 2003.10.27
1729 2003.10.24
1730 2003.10.14
1731 2003.10.06
1733 2003.10.05.d
1734 2003.10.05.c
1735 2003.10.05.b
1737 2003.09.29
1738 2003.09.28
1739 2003.09.21
1740 2003.09.19
1741 2003.09.17
1742 2003.09.14.c
1745 2003.09.13.b
1746 2003.09.13.a
1747 2003.09.12
1748 2003.09.00
1749 2003.08.29
1751 2003.08.12
1752 2003.08.08
1753 2003.07.26.R
1754 2003.07.20
1756 2003.07.09
1757 2003.07.05.b
1758 2003.07.05.a
1759 2003.07.04
1760 2003.07.00.c
1761 2003.07.00.b
1762 2003.07.00.a
1763 2003.06.30
1764 2003.06.26
1765 2003.06.24.c
1767 2003.06.24.a
1768 2003.06.22
1769 2003.06.19
1772 2003.05.25
1773 2003.05.14
1774 2003.05.10
1775 2003.05.07
1778 2003.04.26
1779 2003.04.25
1780 2003.04.23.b
1781 2003.04.23.a
1782 2003.04.21.b
1783 2003.04.21.a
1784 2003.04.20.c
1785 2003.04.20.b
1786 2003.04.20.a
1787 2003.04.19
1788 2003.04.18
1789 2003.04.15
1790 2003.04.11
1791 2003.04.09
1792 2003.04.04
1794 2003.02.27
1795 2003.02.15.b
1796 2003.02.15.a
1797 2003.02.11
1798 2003.02.08
1799 2003.01.17
1800 2003.01.03
1803 2002.12.24
1804 2002.12.21
1805 2002.12.20
1806 2002.12.16
1807 2002.12.01
1808 2002.11.28.b
1809 2002.11.28.a
1812 2002.11.11
1813 2002.11.02
1814 2002.11.00.a
1816 2002.10.14
1817 2002.10.11
1818 2002.10.05.b
1819 2002.10.05.a
1820 2002.10.03
1821 2002.09.30
1822 2002.09.29
1823 2002.09.27.c
1824 2002.09.27.b
1825 2002.09.27.a
1826 2002.09.21.b
1827 2002.09.21.a
1828 2002.09.16.b
1830 2002.09.13
1831 2002.09.09
1832 2002.09.05
1833 2002.08.28
1835 2002.08.14
1836 2002.08.11
1837 2002.08.07
1838 2002.08.06.R
1839 2002.08.05
1840 2002.07.26
1842 2002.07.10
1843 2002.07.09.b
1844 2002.07.09.a
1846 2002.06.20.b
1852 2002.06.11.a
1853 2002.06.09.b
1854 2002.06.09.a
1855 2002.06.03
1856 2002.05.31.b
1857 2002.05.31.a
1858 2002.05.22.b
1859 2002.05.22.a
1860 2002.05.21.R
1861 2002.05.21
1862 2002.05.13
1863 2002.05.10
1864 2002.05.07
1865 2002.04.30
1866 2002.04.21
1867 2002.04.20
1868 2002.04.18
1869 2002.04.12
1870 2002.04.09
1871 2002.04.02
1872 2002.04.01
1873 2002.03.25.b
1875 2002.03.24
1876 2002.03.19
1877 2002.03.15.b
1878 2002.03.15.a
1879 2002.03.03
1880 2002.02.23
1881 2002.02.16
1882 2002.02.11
1883 2002.02.07
1884 2002.01.30.b
1885 2002.01.30.a
1886 2002.01.04
1888 2002.01.01.b
1889 2002.01.01.a
1890 2001.12.21
1891 2001.11.23
1893 2001.11.07
1894 2001.10.07
1896 2001.09.30.b
1897 2001.09.30.a
1898 2001.09.24
1899 2001.09.18
1900 2001.09.16
1901 2001.09.15.b
1902 2001.09.15.a
1903 2001.09.13
1904 2001.09.08
1905 2001.09.07.b
1907 2001.09.03.b
1909 2001.09.02
1910 2001.09.01
1911 2001.08.31
1913 2001.08.27
1914 2001.08.26
1915 2001.08.25
1916 2001.08.22
1917 2001.08.21
1918 2001.08.19.c
1921 2001.08.18.c
1922 2001.08.18.b
1923 2001.08.18.a
1924 2001.08.16
1925 2001.08.12
1927 2001.08.04
1930 2001.07.25
1933 2001.07.15.b
1934 2001.07.15.a
1935 2001.07.06.b
1936 2001.07.06.a
1938 2001.07.00
1939 2001.06.12
1940 2001.06.10
1941 2001.06.09
1943 2001.05.29
1944 2001.05.23
1945 2001.05.20
1946 2001.05.18
1947 2001.05.11
1948 2001.05.08
1949 2001.05.04
1950 2001.05.03
1951 2001.05.00
1952 2001.04.28
1953 2001.04.13.b
1954 2001.04.13.a
1955 2001.04.12.e
1956 2001.04.12.d
1957 2001.04.12.c
1958 2001.04.12.b
1959 2001.04.12.a
1960 2001.04.11.d
1961 2001.04.11.c
1962 2001.04.11.a
1964 2001.04.08.b
1965 2001.04.08.a
1966 2001.04.05
1968 2001.04.02.a
1969 2001.03.23
1970 2001.03.09
1971 2001.03.08
1972 2001.03.03
1976 2001.02.04
1977 2001.01.24.R
1980 2001.01.09
1981 2001.01.06

In [71]:
sharks.caseNumber = sharks.caseNumber.str.replace('.b', '')
sharks.caseNumber = sharks.caseNumber.str.replace('.a', '')
sharks.caseNumber = sharks.caseNumber.str.replace('.R', '')
sharks.caseNumber = sharks.caseNumber.str.replace('.c', '')
sharks.caseNumber = sharks.caseNumber.str.replace('.d', '')
sharks.caseNumber = sharks.caseNumber.str.replace('.e', '')

In [72]:
sharks.loc[847,'caseNumber'] = ['2011.10.29']
sharks.loc[882,'caseNumber'] = ['2011.08.17']
sharks.loc[1135,'caseNumber'] = ['2009.04.17']
sharks.loc[1346,'caseNumber'] = ['2007.08.19']
sharks.loc[370,'caseNumber'] = ['2015.09.01']
sharks.loc[504,'caseNumber'] = ['2014.09.01']
sharks.loc[525,'caseNumber'] = ['2014.08.01']
sharks.loc[588,'caseNumber'] = ['2014.01.01']
sharks.loc[802,'caseNumber'] = ['2012.04.01']
sharks.loc[1024,'caseNumber'] = ['2010.06.01']
sharks.loc[1187,'caseNumber'] = ['2008.12.01']
sharks.loc[1210,'caseNumber'] = ['2008.09.01']
sharks.loc[1239,'caseNumber'] = ['2008.07.01']
sharks.loc[1298,'caseNumber'] = ['2008.10.01']
sharks.loc[1299,'caseNumber'] = ['2008.08.01']
sharks.loc[1314,'caseNumber'] = ['2007.11.01']
sharks.loc[1403,'caseNumber'] = ['2007.02.01']
sharks.loc[1448,'caseNumber'] = ['2006.08.01']
sharks.loc[1709,'caseNumber'] = ['2004.01.01']
sharks.loc[1724,'caseNumber'] = ['2003.11.01']
sharks.loc[1748,'caseNumber'] = ['2003.09.01']
sharks.loc[1760,'caseNumber'] = ['2003.07.01']
sharks.loc[1761,'caseNumber'] = ['2003.07.01']
sharks.loc[1762,'caseNumber'] = ['2003.07.01']
sharks.loc[1814,'caseNumber'] = ['2002.11.01']
sharks.loc[1938,'caseNumber'] = ['2001.07.01']
sharks.loc[1951,'caseNumber'] = ['2001.05.01']

In [73]:
for i,row in sharks.iterrows():
    print(i, row['date'])

2 09-Jun-2018
3 08-Jun-2018
4 04-Jun-2018
5 03-Jun-2018
6 03-Jun-2018
7 27-May-2018
8 26-May-2018
9 26-May-2018
10 24-May-2018
11 21-May-2018
12 13-May-2018
13 13-May-2018
15 12-May-2018
16 09-May-2018
17 Reported 30-Apr-2018
18 28-Apr-2018
19 28-Apr-2018
20 25-Apr-2018
21 25-Apr-2018
22 24-Apr-2018
23 23-Apr-2018
24 22-Apr-2018
25 19-Apr-2018
26 15-Apr-2018
27 15-Apr-2018
28 15-Apr-2018
29 15-Apr-2018
30 14-Apr-2018
31 Reported 10-Apr-2018
33 05-Apr-2018
34 03-Apr-2018
35 31-Mar-2018
36 14-Mar-2018
37 9-Mar-2018
38 9-Mar-2018
39 24-Feb-2018
41 18-Feb-2018
42 15-Feb-2018
45 03-Feb-2018
46 01-Feb-2018
47 28-Jan-2018
48 21-Jan-2018
49 14-Jan-2018
50 13-Jan-2018
51 12-Jan-2018
52 05-Jan-2018
55 21-Dec-2017
57 30-Nov-2017
60 24-Nov-2017
62 Reported 13-Nov-2017
63 13-Nov-2017
64 04-Nov-2017
65 Reported 31-Oct-2017
66 28-Oct-2017
67 26-Oct-2017
68 23-Oct-2017
69 23-Oct-2017
72 21-Oct-2017
73 18-Oct-2017
74 09-Oct-2017
76 01-Oct-2017
77 25-Sep-2017
78 25-Sep-2017
79 24-Sep-2017
80 24-Sep-2017
81 20-Sep-2017
82 16-Sep-2017
83 16-Sep-2017
84 15-Sep-2017
85 15-Sep-2017
87 13-Sep-2017
88 10-Sep-2017
89 10-Sep-2017
90 Reported 06-Sep-2017
91 03-Sep-2017
92 03-Sep-2017
93 02-Sep-2017
95 02-Sep-2017
96 29-Aug-2017
99 26-Aug-2017
100 23-Aug-2017
101 18-Aug-2017
102 10-Aug-2017
104 03-Aug-2017
105 01-Aug-2017
106 31-Jul-2017
107 29-Jul-2017
110 Reported 26-Jul-2017
111 24-Jul-2017
116 20-Jul-2017
117 20-Jul-2017
118 14-Jul-2017
119 14-Jul-2017
120 11-Jul-2017
121 09-Jul-2017
122 Reported 07-Jul-2017
125 29-Jun-2017
127 19-Jun-2017
129 18-Jun-2017
130 17-Jun-2017
131 2017.06.05
133 11-Jun-2017
135 10-Jun-2017
136 Reported 07-Jun-2017
137 04-Jun-2017
140 28-May-2017
141 27-May-2017
142 12-May-2017
143 Reported 06-May-2017
144 05-May-2017
147 29-Apr-2017
149 29-Apr-2017
153 20-Apr-2017
156 14-Apr-2017
157 13-Apr-2017
159 12-Apr-2017
163 06-Apr-2017
165 02-Apr-2017
167 27-Mar-2017
168 19-Mar-2017
169 18-Mar-2017
170 11-Mar-2017
171 Reported 09-Mar-2017
173 24-Feb-2017
174 21-Feb-2017
175 17-Feb-2017
176 11-Feb-2017
178 06-Feb-2017
180 01-Feb-2017
181 24-Jan-2017
182 22-Jan-2017
183 21-Jan-2017
184 13-Jan-2017
185 13-Jan-2017
186 09-Jan-2017
188 05-Jan-2017
189 03-Jan-2017
190 27-Dec-2016
192 19-Dec-2016
193 14-Dec-2016
194 11-Dec-2016
195 11-Dec-2016
196 06-Dec-2016
197 01-Dec-2016
198 28-Nov-2016
200 30-Oct-2016
201 29-Oct-2016
202 24-Oct-2016
203 21-Oct-2016
204 15-Oct-2016
206 13-Oct-2016
207 12-Oct-2016
208 10-Oct-2016
209 02-Oct-2016
210 01-Oct-2016
211 26-Sep-2016
212 18-Sep-2016
213 18-Sep-2016
214 18-Sep-2016
215 17-Sep-2016
216 17-Sep-2016
217 16-Sep-2016
219 11-Sep-2016
221 06-Sep-2016
223 05-Sep-2016
224 04-Sep-2016
225 01-Sep-2016
227 29-Aug-2016
228 29-Aug-2016
229 27-Aug-2016
230 25-Aug-2016
231 07-Aug-2016
232 06-Aug-2016
233 04-Aug-2016
234 29-Jul-2016
235 28-Jul-2016
236 28-Jul-2016
237 27-Jul-2016
238 26-Jul-2016
239 24-Jul-2016
240 23-Jul-2016
241 23-Jul-2016
242 20-Jul-2016
246 15-Jul-2016
247 15-Jul-2016
248 Reported  14-Jul-2016
250 08-Jul-2016
251 07-Jul-2016
252 07-Jul-2016
254 04-Jul-2016
255 27-Jun-2016
256 25-Jun-2016
257 24-Jun-2016
258 23-Jun-2016
259 21-Jun-2016
260 21-Jun-2016
261 15-Jun-2016
262 15-Jun-2016
264 11-Jun-2016
265 07-Jun-2016
266 05-Jun-2016
268 04-Jun-2016
269 02-Jun-2016
270 02-Jun-2016
271 31-May-2016
273 29-May-2016
277 18-May-2016
279 03-May-2016
280 02-May-2016
281 25-Apr-2016
282 23-Apr-2016
283 22-Apr-2016
284 19-Apr-2016
285 18-Apr-2016
286 18-Apr-2016
287 13-Apr-2016
289 08-Apr-2016
290 07-Apr-2016
291 07-Apr-2016
293 30-Mar-2016
294 28-Mar-2016
295 28-Mar-2016
296 26-Mar-2016
298 11-Mar-2016
299 10-Mar-2016
300 04-Mar-2016
301 Reported 03-Mar-2016
302 02-Mar-2016
303 22-Feb-2016
304  19-Feb-2016
306 Reported 10-Feb-2016
307 10-Feb-2016
309 04-Feb-2016
310 02-Feb-2016
311 29-Jan-2016
312 28-Jan-2016
314 24-Jan-2016
315 24-Jan-2016
316 23-Jan-2016
317 Reported 11-Jan-2016
318 05-Jan-2016
319 02-Jan-2016
320 26-Dec-2015
322 22-Dec-2015
323 21-Dec-2015
324 21-Dec-2015
325 19-Dec-2015
327 11-Dec-2015
329 20-Nov-2015
330 16-Nov-2015
332 15-Nov-2015
333 10-Nov-2015
335 03-Nov-2015
337 01-Nov-2015
338 30-Oct-2015
339 28-Oct-2015
340 25-Oct-2015
341 21-Oct-2015
342 19-Oct-2015
344 17-Oct-2015
345 17-Oct-2015
346 13-Oct-2015
348 09-Oct-2015
349 08-Oct-2015
350 07-Oct-2015
351 05-Oct-2015
352 05-Oct-2015
353 04-Oct-2015
354 29-Sep-2015
356 24-Sep-2015
357 20-Sep-2015
358 20-Sep-2015
359 20-Sep-2015
360 20-Sep-2015
361 19-Sep-2015
362 18-Sep-2015
363 17-Sep-2015
364 08-Sep-2015
366 05-Sep-2015
367 04-Sep-2015
368 03-Sep-2015
370 Sep-2015
372 29-Aug-2015
373 22-Aug-2015
374 22-Aug-2015
375 20-Aug-2015
377 18-Aug-2015
378 18-Aug-2015
379 10-Aug-2015
380 31-Jul-2015
381 28-Jul-2015
382 27-Jul-2015
383 26-Jul-2015
385 25-Jul-2015
386 23-Jul-2015
387 23-Jul-2015
388 22-Jul-2015
389 19-Jul-2015
390 10-Jul-2015
391 08-Jul-2015
392 06-Jul-2015
394 04-Jul-2015
395 03-Jul-2015
396 02-Jul-2015
397 01-Jul-2015
398 30-Jun-2015
399 30-Jun-2015
400 27-Jun-2015
401 27-Jun-2015
403 26-Jun-2015
404 26-Jun-2015
405 Reported 25-Jun-2015
406 25-Jun-2015
407 24-Jun-2015
409 23-Jun-2015
410 19-Jun-2015
411 17-Jun-2015
412 14-Jun-2015
416 07-Jun-2015
418 01-Jun-2015
421 25-May-2015
423 20-May2015
424 15-May-2015
425 09-May-2015
426 07-May-2015
427 03-May-2015
428 02-May-2015
430 26-Apr-2015
431 25-Apr-2015
432 24-Jun-2015
433 13-Apr-2015
434 12-Apr-2015
435 11-Apr-2015
436 03-Apr-2015
437 29-Mar-2015
438 31-Mar-2015
439 26-Mar-2015
440 21-Mar-2015
441 18-Mar-2015
442 16-Mar-2015
443 11-Mar-2015
444 10-Mar-2015
445 07-Mar-2015
448 09-Feb-2015
449 08-Feb-2015
450 05-Feb-2015
451 30-Jan-2015
452 27-Jan-2015
453 24-Jan-2015
454 23-Jan-2015
455 19-Jan-2015
457 17-Jan-2015
458 16-Jan-2015
459 08-Jan-2015
461 03-Jan-2015
462 01-Jan-2015
464 29-Dec-2014
467 28-Dec-2014
468 28-Dec-2014
469 Reported 23-Dec-2014
470 15-Dec-2014
471 Reported 03-Dec-2014
472 29-Nov-2014
473 20-Nov-2014
474 19-Nov-2014
476 16-Nov-2014
477 13-Nov-2014
478 10-Nov-2014
479 08-Nov-2014
481 29-Oct-2014
483 20-Oct-2014
485 18-Oct-2014
489 11-Oct-2014
490 05-Oct-2014
492 05-Oct-2014
493 03-Oct-2014
494 03-Oct-2014
495 02-Oct-2014
496 02-Oct-2014
497 21-Sep-2014
499 13-Sep-2014
500 09-Sep-2014
501 06-Sep-2014
503 02-Sep-2014
504 Sep-2014
506 29-Aug-2014
508 28-Aug-2014
510 27-Aug-2014
512 Reported 25-Aug-2014
514 16-Aug-2014
515 12-Aug-2014
516 10-Aug-2014
517 09-Aug-2014
519 08-Aug-2014
520 06-Aug-2014
522 02-Aug-2014
523 02-Aug-2014
524 01-Aug-2014
525 Aug-2014
526 27-Jul-2014
527 22-Jul-2014
528 21-Jul-2014
530 16-Jul-2014
531 14-Jul-2014
532 13-Jul-2014
533 12-Jul-2014
534 9-Jul-2014
535 5-Jul-2014
536 5-Jul-2014
537 3-Jul-2014
538 Reported 27-Jun-2014
539 25-Jun-2014
540 18-Jun-2014
541 18-Jun-2014
542 Reported 17-Jun-2014
543 09-Jun-2014
544 09-Jun-2014
545 09-Jun-2014
546 08-Jun-2014
549 01-Jun-2014
552 23-May-2014
553 22-May-2014
555 14-May-2014
557 11-May-2014
558 Reported 10-May-2014
561 01-May-2014
562 24-Apr-2014
563 22-Apr-2014
564 15-Apr-2014
566 12-Apr-2014
567 04-Apr-2014
568 04-Apr-2014
570 29-Mar-2014
571 22-Mar-2014
572 22-Mar-2014
573 21-Mar-2014
574 18-Mar-2014
575 18-Mar-2014
577 12-Mar-2014
578 13-Mar-2014
579 02-Mar-2014
580 20-Feb-2014
581 Reported 17-Feb-2014
582 08-Feb-2014
583 07-Feb-2014
584 07-Feb-2014
585 26-Jan-2014
586 25-Jan-2014
587 04-Jan-2014
588 2014
590 25-Dec-2013
591 16-Dec-2013
592 13-Dec-2013
593 11-Dec-2013
594 10-Dec-2013
595 05-Dec-2013
596 02-Dec-2013
597 30-Nov-2013
599 23-Nov-2013
600 22-Nov-2013
601 12-Nov-2013
602 10-Nov-2013
603 07-Nov-2013
604 07-Nov-2013
605 31-Oct-2013
607 26-Oct-2013
608 26-Oct-2013
609 24-Oct-2013
610 23-Oct-2013
611 20-Oct-2013
612 19-Oct-2013
613 11-Oct-2013
614 08-Oct-2013
615 06-Oct-2013
616 10-Oct-2013
617 29-Sep-2013
618 29-Sep-2013
619  25-Sep-2013
620  21-Sep-2013
621  21-Sep-2013
622  14-Sep-2013
625  07-Sep-2013
626  07-Sep-2013
627  02-Sep-2013
628  01-Sep-2013
629  01-Sep-2013
630  01-Sep-2013
631 31-Aug-2013
632 31-Aug-2013
634 26-Aug-2013
636  25-Aug-2013
637  18-Aug-2013
641 11-Aug-2013
642 Reported 08-Aug-2013
643  05-Aug-2013
645   30-Jul-2013
646 28-Jul-2013
648   29-Jul-2013
649 28-Jul-2013
650 28-Jul-2013
653 Reported 17-Jul-2013
655 14-Jul-2013
657 07-Jul-2013
658 02-Jul-2013
659 30-Jun-2013
660 27-Jun-2013
661 25-Jun-2013
662 25-Jun-2013
663 25-Jun-2013
664 18-Jun-2013
665 17-Jun-2013
666 16-Jun-2013
669 06-Jun-2013
670 06-Jun-2013
671 27-May-2013
672 27-May-2013
673 23-May-2013
674 23-May-2013
675 14-May-2014
676 08-May-2013
677 08-May-2013
678 04-May-2013
679 28-Apr-2013
681 21-Apr-2013
682 17-Apr-2013
683 14-Apr-2013
684 13-Apr-2013
685 13-Apr-2013
686 10-Apr-2013
687 04-Apr-2013
688 Reported 02-Apr-2013
689 02-Apr-2013
690 31-Mar-2013
691 29-Mar-2013
693 21-Mar-2013
694 16-Mar-2013
695 16-Mar-2013
696 12-Mar-2013
697 10-Mar-2013
698 10-Mar-2013
699 03-Mar-2013
700 27-Feb-2013
702 21-Feb-2013
703 10-Feb-2013
704 09-Feb-2013
705 01-Feb-2013
706 26-Jan-2013
707 25-Jan-2013
708 Reported 21-Jan-2013
709 16-Jan-2013
710 13-Jan-2013
711 05-Jan-2013
712 31-Dec-2012
713 30-Dec-2012
714 28-Dec-2012
715 25-Dec-2012
716 19-Dec-2012
717 05-Dec-2012
718 02-Dec-2012
720 30-Nov-2012
721 27-Nov-2012
722 22-Nov-2012
723 19-Nov-2012
724 04-Nov-2012
725 04-Nov-2012
726 30-Oct-2012
728 23-Oct-2012
730 18-Oct-2012
731 18-Oct-2012
732 16-Oct-2012
734 10-Oct-2012
735 02-Oct-2012
736 25-Sep-2012
737 24-Sep-2012
738 16-Sep-2012
741 08-Sep-2012
742 08-Sep-2012
743 06-Sep-2012
744 06-Sep-2012
745 04-Sep-2012
749 31-Aug-2012
750 28-Aug-2012
751 26-Aug-2012
752 15-Aug-2012
754 08-Aug-2012
755 06-Aug-2012
756 04-Aug-2012
757 31-Jul-2012
758 31-Jul-2012
759 30-Jul-2012
760 30-Jul-2012
761 24-Jul-2012
762 23-Jul-2012
763 21-Jul-2012
765 14-Jul-2012
767 07-July-2012
769 07-Jul-2012
770 06-Jul-2012
772 26-Jun-2012
773 26-Jun-2012
775 22-Jun-2012
776 22-Jun-2012
777 20-Jun-2012
778 19-Jun-2012
780 15-Jun-2012
782 14-Jun-2012
783 14-Jun-2012
784 14-Jun-2012
785 12-Jun-2012
786 10-Jun-2012
787 03-Jun-2012
789 02-Jun-2012
791 29-May-2012
792 23-May-2012
793 20-May-2012
794 16-May-2012
795 12-May-2012
798 19-Apr-2012
799 19-Apr-2012
800 11-Apr-2012
801 03-Apr-2012
802 Apr-2013
803 31-Mar-2012
804 24-Mar-2012
806 20-Mar-2012
807 15-Mar-2012
809 14-Mar-2012
810 06-Mar-2012
812 05-Mar-2012
813 04-Mar-2012
814 03-Mar-2012
815 01-Mar-2012
816 26-Feb-2012
817 25-Feb-2012
819 06-Feb-2012
821 19-Jan-2012
822 Reported 22-Jan-2012
823 18-Jan-2012
824 18-Jan-2012
825 15-Jan-2012
826 13-Jan-2012
827 03-Jan-2012
828 02-Jan-2012
829 31-Dec-2011
830 Reported 26-Dec-2011
831 25-Dec-2011
832 23-Dec-2011
833 21-Dec-2011
834 21-Dec-2011
835 11-Dec-2011
836 07-Dec-2011
837 07-Dec-2011
840 02-Dec-2011
841 29-Nov-2011
842 28-Nov-2011
843 22-Nov-2011
844 Reported 20-Nov-2011
845 12-Nov-2011
846 11-Nov-2011
847   29-Oct-2011
848 Reported 28-Oct-2011
850 22-Oct-2011
851 20-Oct-2011
852 19-Oct-2011
853 11-Oct-2011
854 10-Oct-2011
855 09-Oct-2011
856 05-Oct-2011
857 02-Oct-2011
858 01-Oct-2011
859 30-Sep-2011
860 28-Sep-2011
861 28-Sep-2011
862 24-Sep-2011
863 24-Sep-2011
864 20-Sep-2011
865 19-Sep-2011
866 17-Sep-2011
867 16-Sep-2011
868 11-Sep-2011
869 11-Sep-2011
871 04-Sep-2011
872 02-Sep-2011
873 31-Aug-2011
874 28-Aug-2011
876 26-Aug-2011

877 24-Aug-2011
878 24-Aug-2011
879 23-Aug-2011
880 18-Aug-2011
882 17-Aug-2011
883 17-Aug-2011
884 16-Aug-2011
885 16-Aug--2011
886 16-Aug-2011
887 15-Aug-2011
888 11-Aug--2011
889 01-Aug-2011
890 31-Jul-2011
891 30-Jul-2011
892 25-Jul-2011
893 22-Jul-2011
895 15-Jul-2011
896 13-Jul-2011
897 13-Jul-2011
898 07-Jul-2011
899 07-Jul-2011
900 06-Jul-2011
901 05-Jul-2011
902 30-Jun-2011
903 29-Jun-2011
904 28-Jun-2011
906 24-Jun-2011
907 21-Jun-2011
908 19-Jun-2011
909 19-Jun-2011
910 15-Jun-2011
912 12-Jun-2011
913 Reported 06-Jun-2011
914 06-Jun-2011
915 06-Jun-2011
918 29-May-2011
921 21-May-2011
922 13-May-2011
923 21-May-2011
924 13-May-2011
925 10-May-2011
926 Reported 07-May-2011
927 04-May-2011
928 26-Apr-2011
929 23-Apr-2011
930 22-Apr-2011
931 16-Apr-2011
932 13-Apr-2011
933 08-Apr-2011
934 Reported 29-Mar-2011
936 23-Mar-2011
937 21-Mar-2011
938 21-Mar-2011
941 10-Mar-2011
942 Reported 28-Feb-2011
943 23-Feb-2011
944 18-Feb-2011
945 17-Feb-2011
946 13-Feb-2011
947 12-Feb-2011
948 Reported 04-Feb-2011
949 02-Feb-2011
951 28-Jan-2011
952 26-Jan-2011
954 15-Jan-2011
955 Reported 12-Jan 2011
957 26-Dec-2010
958 17-Dec-2010
959 11-Dec-2010
961 Reported 03-Dec-2010
962 01-Dec-2010
963 01-Dec-2010
966 Reported 27-Nov-2010
967 27-Nov-2010
968 19-Nov-2010
969 15-Nov-2010
970 14-Nov-2010
971 Reported 12-Nov-2010
973 Reported 28-Oct-2010
974 28-Oct-2010
975 25-Oct-2010
976 23-Oct-2010
977 23-Oct-2010
978 22-Oct-2010
980 09-Oct-2010
981 02-Oct-2010
983 01-Oct-2010
984 27-Sep-2010
985 24-Sep-2010
986 21-Sep-2010
987  13-Sep-2010
988 07-Sep-2010
989 Reported 06-Sep-2010
990  04-Sep-2010
991 03-Sep-2010
992 03-Sep-2010
993 02-Sep-2010
994 29-Aug-2010
995 18-Aug-2010
996 17-Aug-2010
997 14-Aug-2010
1000 08-Aug-2010
1001 07-Aug-2010
1002 07-Aug-2010
1004 02-Aug-2010
1006 25-Jul-2010
1007 23-Jul-2010
1008 19-Jul-2010
1010 17-Jul-2010
1011 16-Jul-2010
1012 16-Jul-2010
1013 11-Jul-2010
1015 03-Jul-2010
1016 02-Jul-2010
1017 02-Jul-2010
1018 27-Jun-2010
1021 15-Jun-2010
1023 06-Jun-2010
1024 Jun-2010
1025 30-May-2010
1028 18-May-2010
1029 03-May-2010
1031 28-Apr-2010
1032 19-Apr-2010
1033 13-Apr-2010
1034 04-Apr-2010
1035  27-Mar-2010
1036 190Feb-2010
1037 16-Feb-2010
1038 15-Feb-2010
1040 11-Feb-2010
1041 Reported 06-Feb-2010
1042 06-Feb-2010
1043 06-Feb-2010
1044 04-Feb-2010
1045 03-Feb-2010
1047 31-Jan-2010
1048 27-Jan-2010
1049 22-Jan-2010
1050 22-Jan-2010
1051 12-Jan-2010
1054 09-Jan-2010
1055 09-Jan-2010
1056 06-Jan-2010
1057 05-Jan-2010
1058 29-Dec-2009
1059 26-Dec-2009
1060 22-Dec-2009
1061 20-Dec-2009
1062 20-Dec-2009
1063 18-Dec-2009
1064 18-Dec-2009
1065 16-Dec-2009
1066 13-Dec-2009
1068 05-Dec-2009
1069 25-Nov-2009
1070 24-Nov-2009
1071 16-Nov-2009
1072 16-Nov-2009
1074 11-Nov-2009
1075 08-Nov-2009
1076 05-Nov-2009
1077 30-Oct-2009
1078 Reported 29-Oct-2009
1080 24-Oct-2009
1081 19-Oct-2009
1083 17-Oct-2009
1084 Reported 14-Oct-2009
1085 09-Oct-2009
1086 02-Oct-2009
1087 26-Sep-2009
1088 18-Sep-2009
1089 15-Sep-2009
1090 13-Sep-2009
1091 12-Sep-2009
1092 07-Sep-2009
1093 02-Sep-2009
1094 01-Sep-2009
1095 30-Aug-2009
1096 29-Aug-2009
1098 11-Aug-2009
1099 10-Aug-2009
1100 06-Aug-2009
1101 01-Aug-2009
1102 31-July-2009
1103 30-Jul-2009
1105 Reported 24-Jul-2009
1110 18-Jul-2009
1111 11-Jul-2009
1112 11-Jul-2009
1113 07-Jul-2009
1116 27-Jun-2009
1117 21-Jun-2009
1118 16-Jun-2009
1119 Reported 14-Jun-2009
1120 02-Jun-2009
1121 02-Jun-2009
1123 31-May-2009
1124 25-May-2009
1125 17-May-2009
1126 16-May-2009
1127 16-May-2009
1128 12-May-2009
1129 06-Mar-2009
1131 Reported 25-Apr-2009
1132 21-Apr-2009
1133 20-Apr-2009
1134 19-Apr-2009
1135 17-Apr-2009
1136 11-Apr-2009
1137 12-Apr-2009
1138 06-Apr-2009
1139 06-Apr-2009
1140 03-Apr-2009
1141 27-Mar-2009
1142 21-Mar-2009
1143 20-Mar-2009
1144 19-Mar-2009
1148 17-Mar-2009
1149 Reported 16-Mar-2009
1150 06-Mar-2009
1151 02-Mar-2009
1152 01-Mar-2009
1153 01-Mar-2009
1154 22-Feb-2009
1155 18-Feb-2009
1156 12-Feb-2009
1157 11-Feb-2009
1158 08-Feb-2009
1159 07-Feb-2009
1160 07-Feb-2009
1161 Reported 27-Jan-2009
1162 Reported 26-Jan-2009
1163 25-Jan-2009
1165 24-Jan-2009
1166 24-Jan-2009
1167 23-Jan-2009
1168 18-Jan-2009
1169 16-Jan-2009
1171 12-Jan-2009
1173 11-Jan-2009
1175 10-Jan-2009
1176 06-Jan-2009
1180 27-Dec-2008
1181 27-Dec-2008
1182 27-Dec-2008
1183 20-Dec-2008
1184 14-Dec-2008
1185 10-Dec-2008
1187 Dec-2008
1189 25-Nov-2008
1191 09-Nov-2008
1192 09-Nov-2008
1193 06-Nov-2008
1194 22-Oct-2008
1195 21-Oct-2008
1196 12-Oct-2008
1197 11-Oct-2008
1198 08-Oct-2008
1199 06-Oct-2008
1200 28-Sep-2008
1201 28-Sep-2008
1202 15-Sep-2008
1203 14-Sep-2008
1204 09-Sep-2008
1205 08-Sep-2008
1206 07-Sep-2008
1207 06-Sep-2008
1208 06-Sep-2008
1209 01-Sep-2008
1210 Sep-2008
1211 30-Aug-2008
1212 30-Aug-2008
1213 30-Aug-2008
1214 28-Aug-2008
1215 27-Aug-2008
1216 24-Aug-2008
1218 20-Aug-2008
1219 18-Aug-2008
1222 11-Aug-2008
1223 30-Jul-2008
1224 Reported 30-Jul-2008
1225 27-Jul-2008
1226 26-Jul-2008
1227 26-Jul-2008
1228 25-Jul-2008
1230 24-Jul-2008
1232 23-Jul-2008
1233 19-Jul-2008
1234 18-Jul-2008
1235 13-Jul-2008
1236 11-Jul-2008
1239 Late Jul-2008
1240 28-Jun-2008
1241 28-Jun-2008
1242 28-Jun-2008
1243 Reported 26-Jun-2008
1244 26-Jun-2008
1245 26-Jun-2008
1246 24-Jun-2008
1249 11-Jun-2008
1250 07-Jun-2008
1253 01-Jun-2008
1254 26-May-2008
1255 24-May-2008
1256 24-May-2008
1257 23-May-2008
1258 14-May-2008
1259 10-May-2008
1260 07-May-2008
1261 07-May-2008
1262 01-May-2008
1263 28-Apr-2008
1264 28-Apr-2008
1265 27-Apr-2008
1266 26-Apr-2008
1267 26-Apr-2008
1268 25-Apr-2008
1269 20-Apr-2008
1270 20-Apr-2008
1271 Reported 19-Apr-2008
1272 18-Apr-2008
1273 17-Apr-2008
1274 15-Apr-2008
1275 Reported 09-Apr-2008
1276 25-Mar-2008
1278 08-Apr-2008
1279 03-Apr-2008
1280 28-Mar-2008
1281 28-Mar-2008
1282 28-Mar-2008
1283 23-Mar-2008
1284 21-Mar-2008
1285 15-Mar-2008
1286 07-Mar-2008
1287 24-Feb-2008
1288 Reported 21-Feb-2008
1289 15-Feb-2008
1291 06-Feb-2008
1292 2008.01.30
1293 29-Jan-2008
1294 27-Jan-2008
1295 Reported 19-Jan-2008
1297 10-Jan-2008
1298 Fall 2008
1299 Summer-2008
1300 21-Dec-2007
1301 19-Dec-2007
1302 18-Dec-2007
1303 15-Dec-2007
1304 14-Dec-2007
1305 10-Dec-2007
1307 07-Dec-2007
1308 18-Nov-2007
1309 08-Nov-2007
1310 07-Nov-2007
1311 06-Nov-2007
1312 04-Nov-2007
1313 03-Nov-2007
1314 November 2011
1315 29-Oct-2007
1317 13-Oct-2007
1318 07-Oct-2007
1319 06-Oct-2007
1320 30-Sep-2007
1321 30-Sep-2007
1328 20-Sep-2007
1329 17-Sep-2007
1330 16-Sep-2007
1332 13-Sep-2007
1335 04-Sep-2007
1337 03-Sep-2007
1338 28-Aug-2007
1339 28-Aug-2007
1340 26-Aug-2007
1341 25-Aug-2007
1342 22-Aug-2007
1343 20-Aug-2007
1344 19-Aug-2007
1345 19-Aug-2007
1346 19-Aug-2007
1347 15-Aug-2007
1349 11-Aug-2007
1350 09-Aug-2007
1351 09-Aug-2007
1353 29-Jul-2007
1354 28-Jul-2007
1355 22-Jul-2007
1356 21-Jul-2007
1357 19-Jul-2007.b
1358 19-Jul-2007.a
1359 18-Jul-2007
1360 18-Jul-2007
1364 05-Jul-2007
1365 04-Jul-2007
1367 30-Jun-2007
1369 25-Jun-2007
1370 24-Jun-2007
1373 05-Jun-2007
1376 Reported 17-May-2007
1378 12-May-2007
1380 Reported 09-May-2007
1381 08-May-2007
1383 07-May-2007
1387 22-Apr-2007
1388 20-Apr-2007
1390 09-Apr-2007
1391 01-Apr-2007
1392 31-Mar-2007
1393 31-Mar-2007
1395 21-Mar-2007
1397 Reported 14-Mar-2007
1399 11-Mar-2007
1400 Reported 05-Mar-2007
1401 04-Feb-2007
1402 03-Feb-2007
1403 Feb-2007
1404 25-Jan-2007
1406 23-Jan-2007
1407 19-Jan-2007
1408 14-Jan-2007
1409 09-Jan-2007
1410 07-Jan-2007
1411 01-Jan-2007
1412 18-Dec-2006
1413 11-Dec-2006
1414 10-Dec-2006
1415 06-Dec-2006
1416 02-Dec-2006
1418 11-Nov-2006
1419 09-Nov-2006
1420 31-Oct-2006
1421 16-Oct-2006
1422 10-Oct-2006
1423 07-Oct-2006
1424 05-Oct-2006
1427 30-Sep-2006
1428 29-Sep-2006
1429 Reported 18-Sep-2006
1430 16-Sep-2006
1431 14-Sep-2006
1432 11-Sep-2006
1433 04-Sep-2006
1434 03-Sep-2006
1435 03-Sep-2006
1436 02-Sep-2006
1437 02-Sep-2006
1438 29-Aug-2006
1439 29-Aug-2006
1440 27-Aug-2006
1441 22-Aug-2006
1442 22-Aug-2006
1443 20-Aug-2006
1444 20-Aug-2006
1445 15-Aug-2006
1446 13-Aug-2006
1448 Early Aug-2006
1450 31-Jul-2006
1451 29-Jul-2006
1452 29-Jul-2006
1453 28-Jul-2006
1454 25-Jul-2006
1455 23-Jul-2006
1457 17-Jul-2006
1460 10-Jul-2006
1461 09-Jul-2006
1462 09-Jul-2006.
1464 08-Jul-2006
1466 July 2006
1468 26-Jun-2006
1469 24-Jun-2006
1471 18-Jun-2006
1472 17-Jun-2006
1473 15-Jun-2006
1475 05-Jun-2006
1476 31-May-2006
1478 27-May-2006
1479 24-May-2006
1480 21-May-2006
1482 05-May-2006
1484 02-May-2006
1485 Reported      23-Apr-2006
1486 21-Apr-2006
1488 13-Apr-2006
1489 11-Apr-2006
1490 09-Apr-2006
1491 09-Apr-2006
1492 03-Apr-2006
1493 Reported  28-Mar-2006
1495 22-Mar-2006
1496 18-Mar-2006
1497 15-Mar-2006
1499 23-Feb-2006
1500 13-Feb-2006
1501 12-Feb-2006
1502 12-Feb-2006
1503 08-Feb-2006
1505 01-Feb-2006
1506 Reported 28-Jan-2006
1507 25-Jan-2006

1509 18-Jan-2006
1510 15-Jan-2006
1511 11-Jan-2006
1513 04-Jan-2006
1514 01-Jan-2006
1515 24-Dec-2005
1516 21-Dec-2005
1518 11-Dec-2005
1520 Reported 29-Nov-2005
1521 27-Nov-2005
1523 25-Nov-2005
1524 25-Nov-2005
1526 21-Nov-2005
1527 20-Nov-2005
1529 15-Nov-2005
1530 12-Nov-2005
1531 02-Nov-2005
1532 02-Nov-2005
1533 29-Oct-2005
1534 25-Oct-2005
1535 22-Oct-2005
1536 21-Oct-2005
1538 15-Oct-2005
1539 13-Oct-2005
1541 06-Oct-2005
1542 03-Oct-2005
1543 01-Oct-2005
1544 Reported      27-Sep-2005
1545 24-Sep-2005
1546 23-Sep-2005
1547 22-Sep-2005
1549 11-Sep-2005
1550 07-Sep-2005
1552 04-Sep-2005
1553 02-Sep-2005
1554 02-Sep-2005
1555 24-Aug-2005
1556 24-Aug-2005
1557 22-Aug-2005
1558 21-Aug-2005
1559 19-Aug-2005
1561 12-Aug-2005
1562 6-Aug-2005
1563 1-Aug-2005
1565 23-Jul-2005
1566 22-Jul-2005
1567 17-Jul-2005
1568 17-Jul-2005
1570 15-Jul-2005
1572 1-Jul-2005
1573 27-Jun-2005
1576 20-Jun-2005
1577 18-Jun-2005
1578 16-Jun-2005
1581 05-Jun-2005
1582 04-Jun-2005
1583 02-Jun-2005
1584 28-May-2005
1586 25-May-2005
1587 15-May-2005
1589 03-May-2005
1590 02-May-2005
1591 02-May-2005
1592 25-Apr-2005
1594 16-Apr-2005
1595 16-Apr-2005
1597 09-Apr-2005
1598 07-Apr-2005
1601 28-Mar-2005
1602 Reported    27-Mar-2005
1603 25-Mar-2005
1604 19-Mar-2005
1605 12-Mar-2005
1606 10-Mar-2005
1607 09-Mar-2005
1608 05-Mar-2005
1609 26-Feb-2005
1610 22-Feb-2005
1611 16-Feb-2005
1612 13-Feb-2005
1613 04-Feb-2005
1614 20-Jan-2005
1615 19-Jan-2005
1617 08-Jan-2005
1619 16-Dec-2004
1620 11-Dec-2004
1621 27-Nov-2004
1622 26-Nov-2004
1625 11-Nov-2004
1627 31-Oct-2004
1629 30-Oct-2004
1630 21-Oct-2004
1631 10-Oct-2004
1632 09-Oct-2004
1633 09-Oct-2004
1634 06-Oct-2004
1635 02-Oct-2004
1636 01-Oct-2004
1638 20-Sep-2004
1639 10-Sep-2004
1643 21-Aug-2004
1644 20-Aug-2004
1645 15-Aug-2004
1646 06-Aug-2004
1647 03-Aug-2004
1650 30-Jul-2004
1654 25-Jul-2004
1656 15-Jul-2004
1657 10-Jul-2004
1659 02-Jul-2004
1660 26-Jun-2004
1661 26-Jun-2004
1663 10-Jun-2004
1664 10-Jun-2004
1665 02-Jun-2004
1666 29-May-2004
1667 23-May-2004
1668 28-May-2004
1669 23-May-2004
1670 22-May-2004
1673 18-May-2004
1674 04-May-2004
1675 01-May-2004
1676 26-Apr-2004
1678 13-Apr-2004
1679 13-Apr-2004
1680 07-Apr-2004
1681 05-Apr-2004
1683 31-Mar-2004
1684 31-Mar-2004
1685 29-Mar-2004
1686 28-Mar-2004
1687 27-Mar-2004
1688 27-Mar-2004
1690 22-Mar-2004
1691 16-Mar-2004
1692 06-Mar-2004
1693 29-Feb-2004
1694 26-Feb-2004
1695 21-Feb-2004
1696 16-Feb-2004
1697 14-Feb-2004
1698 11-Feb-2004
1699 25-Jan-2004
1700 23-Jan-2004
1701 22-Jan-2004
1702 21-Jan-2004
1703 21-Jan-2004
1704 Reported 15-Jan-2004
1705 12-Jan-2004
1706 07-Jan-2004
1707 03-Jan-2004
1709 2004
1711 26-Dec-2003
1712 13-Dec-2003
1713 13-Dec-2003
1714 08-Dec-2003
1715 30-Nov-2003
1716 30-Nov-2003
1717 27-Nov-2003
1719 12-Nov-2003
1720 12-Nov-2003
1721 06-Nov-2003
1723 01-Nov-2003
1724 Nov-2003
1725 31-Oct-2003
1726 31-Oct-2003
1728 27-Oct-2003
1729 24-Oct-2003
1730 14-Oct-2003
1731 06-Oct-2003
1733 05-Oct-2003
1734 05-Oct-2003
1735 05-Oct-2003
1737 29-Sep-2003
1738 28-Sep-2003
1739 21-Sep-2003
1740 19-Sep-2003
1741 17-Sep-2003
1742 14-Sep-2003
1745 13-Sep-2003
1746 13-Sep-2003
1747 12-Sep-2003
1748 Sep-2003
1749 29-Aug-2003
1751 12-Aug-2003
1752 08-Aug-2003
1753 Reported 26-Jul-2003
1754 20-Jul-2003
1756 10-Jul-2003
1757 05-Jul-2003
1758 05-Jul-2003
1759 04-Jul-2003
1760 Jul-2003
1761 Late Jul-2003
1762 Jul-2003
1763 30-Jun-2003
1764 26-Jun-2003
1765 24-Jun-2003
1767 24-Jun-2003
1768 22-Jun-2003
1769 19-Jun-2003
1772 25-May-2003
1773 14-May-2003
1774 10-May-2003
1775 07-May-2003
1778 26-Apr-2003
1779 25-Apr-2003
1780 23-Apr-2003
1781 23-Apr-2003
1782 21-Apr-2003
1783 21-Apr-2003
1784 20-Apr-2003
1785 20-Apr-2003
1786 20-Apr-2003
1787 19-Apr-2003
1788 18-Apr-2003
1789 15-Apr-2003
1790 11-Apr-2003
1791 09-Apr-2003
1792 04-Apr-2003
1794 27-Feb-2003
1795 15-Feb-2003
1796 15-Feb-2003
1797 11-Feb-2003
1798 08-Feb-2003
1799 17-Jan-2003
1800 03-Jan-2003
1803 24-Dec-2002
1804 21-Dec-2002
1805 20-Dec-2002
1806 16-Dec-2002
1807 01-Dec-2002
1808 28-Nov-2002
1809 28-Nov-2002
1812 11-Nov-2002
1813 02-Nov-2002
1814 Nov-2002
1816 14-Oct-2002
1817 11-Oct-2002
1818 05-Oct-2002
1819 05-Oct-2002
1820 03-Oct-2002
1821 30-Sep-2002
1822 29-Sep-2002
1823 27-Sep-2002
1824 27-Sep-2002
1825 27-Sep-2002
1826 21-Sep-2002
1827 21-Sep-2002
1828 16-Sep-2002
1830 13-Sep-2002
1831 09-Sep-2002
1832 05-Sep-2002
1833 28-Aug-2002
1835 14-Aug-2002
1836 11-Aug-2002
1837 07-Aug-2002
1838 Reported 06-Aug-2002
1839 05-Aug-2002
1840 26-Jul-2002
1842 10-Jul-2002
1843 09-Jul-2002
1844 10-Jul-2002
1846 20-Jun-2002
1852 10-Jun-2002
1853 09-Jun-2002
1854 09-Jun-2002
1855 03-Jun-2002
1856 31-May-2002
1857 31-May-2002
1858 22-May-2002
1859 22-May-2002
1860 Reported 21-May-2002
1861 21-May-2002
1862 13-May-2002
1863 10-May-2002
1864 07-May-2002
1865 30-Apr-2002
1866 21-Apr-2002
1867 20-Apr-2002
1868 18-Apr-2002
1869 12-Apr-2002
1870 09-Apr-2002
1871 02-Apr-2002
1872 01-Apr-2002
1873 25-Mar-2002
1875 24-Mar-2002
1876 19-Mar-2002
1877 15-Mar-2002
1878 15-Mar-2002
1879 03-Mar-2002
1880 23-Feb-2002
1881 16-Feb-2002
1882 11-Feb-2002
1883 07-Feb-2002
1884 30-Jan-2002
1885 30-Jan-2002
1886 04-Jan-2002
1888 01-Jan-2002
1889 01-Jan-2002
1890 21-Dec-2001
1891 23-Nov-2001
1893 07-Nov-2001
1894 07-Oct-2001
1896 30-Sep-2001
1897 30-Sep-2001
1898 24-Sep-2001
1899 18-Sep-2001
1900 16-Sep-2001
1901 15-Sep-2001
1902 15-Sep-2001
1903 13-Sep-2001
1904 08-Sep-2001
1905 07-Sep-2001
1907 03-Sep-2001
1909 02-Sep-2001
1910 01-Sep-2001
1911 31-Aug-2001
1913 27-Aug-2001
1914 26-Aug-2001
1915 25-Aug-2001
1916 22-Aug-2001
1917 21-Aug-2001
1918 19-Aug-2001
1921 18-Aug-2001
1922 18-Aug-2001
1923 18-Aug-2001
1924 16-Aug-2001
1925 12-Aug-2001
1927 04-Aug-2001
1930 25-Jul-2001
1933 15-Jul-2001
1934 15-Jul-2001
1935 06-Jul-2001
1936 06-Jul-2001
1938 Jul-2001
1939 12-Jun-2001
1940 10-Jun-2001
1941 09-Jun-2001
1943 29-May-2001
1944 23-May-2001
1945 20-May-2001
1946 18-May-2001
1947 11-May-2001
1948 08-May-2001
1949 04-May-2001
1950 03-May-2001
1951 May-2001
1952 28-Apr-2001
1953 13-Apr-2001
1954 13-Apr-2001
1955 12-Apr-2001
1956 12-Apr-2001
1957 12-Apr-2001
1958 12-Apr-2001
1959 12-Apr-2001
1960 11-Apr-2001
1961 11-Apr-2001
1962 11-Apr-2001
1964 08-Apr-2001
1965 08-Apr-2001
1966 05-Apr-2001
1968 02-Apr-2001
1969 23-Mar-2001
1970 09-Mar-2001
1971 08-Mar-2001
1972 03-Mar-2001
1976 04-Feb-2001
1977 Reported  24-Jan-2001
1980 09-Jan-2001
1981 06-Jan-2001

In [74]:
sharks.date = sharks.date.str.replace('Reported ', '')
sharks.loc[37,'date'] = ['09.Mar.2018']
sharks.loc[38,'date'] = ['09.Mar.2018']
sharks.loc[131,'date'] = ['05.Jun.2017']
sharks.loc[248,'date'] = ['14.Jul.2016']
sharks.loc[304,'date'] = ['19.Feb.2016']
sharks.loc[370,'date'] = ['01.Sep.2015']
sharks.loc[423,'date'] = ['20.May.2015']
sharks.loc[504,'date'] = ['01.Sep.2014']
sharks.loc[525,'date'] = ['01.Aug.2014']
sharks.loc[534,'date'] = ['09.Jul.2014']
sharks.loc[535,'date'] = ['05.Jul.2014']
sharks.loc[536,'date'] = ['05.Jul.2014']
sharks.loc[537,'date'] = ['03.Jul.2014']
sharks.loc[588,'date'] = ['01.Jan.2014']
sharks.loc[619,'date'] = ['25.Sep.2013']
sharks.loc[620,'date'] = ['21.Sep.2013']
sharks.loc[621,'date'] = ['21.Sep.2013']
sharks.loc[622,'date'] = ['14.Sep.2013']
sharks.loc[625,'date'] = ['07.Sep.2013']
sharks.loc[626,'date'] = ['07.Sep.2013']
sharks.loc[627,'date'] = ['02.Sep.2013']
sharks.loc[628,'date'] = ['01.Sep.2013']
sharks.loc[629,'date'] = ['01.Sep.2013']
sharks.loc[630,'date'] = ['01.Sep.2013']
sharks.loc[636,'date'] = ['25.Aug.2013']
sharks.loc[637,'date'] = ['18.Aug.2013']
sharks.loc[643,'date'] = ['05.Aug.2013']
sharks.loc[645,'date'] = ['30.Jul.2013']
sharks.loc[648,'date'] = ['29.Jul.2013']
sharks.loc[767,'date'] = ['07.Jul.2012']
sharks.loc[802,'date'] = ['01.Apr.2012']
sharks.loc[847,'date'] = ['29.Oct.2011']
sharks.loc[885,'date'] = ['16.Aug.2011']
sharks.loc[888,'date'] = ['11.Aug.2011']
sharks.loc[987,'date'] = ['13.Sep.2010']
sharks.loc[990,'date'] = ['04.Sep.2010']
sharks.loc[1024,'date'] = ['01.Jun.2010']
sharks.loc[1035,'date'] = ['27.Mar.2010']
sharks.loc[1036,'date'] = ['19.Feb.2010']
sharks.loc[1102,'date'] = ['31.Jul.2009']
sharks.loc[1187,'date'] = ['01.Dec.2008']
sharks.loc[1210,'date'] = ['01.Sep.2008']
sharks.loc[1239,'date'] = ['01.Jul.2008']
sharks.loc[1292,'date'] = ['30.Jan.2008']
sharks.loc[1298,'date'] = ['01.Oct.2008']
sharks.loc[1299,'date'] = ['01.Aug.2008']
sharks.loc[1314,'date'] = ['01.Nov.2007']
sharks.loc[1357,'date'] = ['19.Jul.2007']
sharks.loc[1358,'date'] = ['19.Jul.2007']
sharks.loc[1403,'date'] = ['01.Feb.2007']
sharks.loc[1448,'date'] = ['01.Aug.2006']
sharks.loc[1462,'date'] = ['09.Jul.2006']
sharks.loc[1466,'date'] = ['30.Jun.2006']
sharks.loc[1485,'date'] = ['23.Apr.2006']
sharks.loc[1493,'date'] = ['28.Mar.2006']
sharks.loc[1544,'date'] = ['27.Sep.2005']
sharks.loc[1562,'date'] = ['06.Aug.2005']
sharks.loc[1563,'date'] = ['01.Aug.2005']
sharks.loc[1573,'date'] = ['27.Jun.2005']
sharks.loc[1602,'date'] = ['27.Mar.2005']
sharks.loc[1709,'date'] = ['01.Jan.2004']
sharks.loc[1724,'date'] = ['01.Nov.2003']
sharks.loc[1748,'date'] = ['01.Sep.2003']
sharks.loc[1760,'date'] = ['01.Jul.2003']
sharks.loc[1761,'date'] = ['01.Jul.2003']
sharks.loc[1762,'date'] = ['01.Jul.2003']
sharks.loc[1814,'date'] = ['01.Nov.2002']
sharks.loc[1938,'date'] = ['01.Jul.2001']
sharks.loc[1951,'date'] = ['01.May.2001']
sharks.loc[1977,'date'] = ['24.Jan.2001']

In [75]:
sharks[['area']] = sharks[['area']].fillna('Unknown')
sharks[['location']] = sharks[['location']].fillna('Unknown')
sharks[['activity']] = sharks[['activity']].fillna('Unknown')
sharks[['species']] = sharks[['species']].fillna('Unknown')

In [76]:
for i,row in sharks.iterrows():
    print(i, row['time'])

2 07h45
3 nan
4 nan
5 nan
6 Late afternoon
7 nan
8 17h00
9 14h00
10 Morning
11 nan
12 15h00
13 08h15
15 11h00
16 10h30
17 nan
18 10h40
19 16h50
20 07h00
21 09h30
22 Afternoon
23 21h50
24 09h40
25 nan
26 nan
27 nan
28 nan
29 08h00
30 09h30
31 nan
33 18h00
34 15h00
35 09h30
36 17h35
37 15h30
38 07h30
39 nan
41 Night
42 16h00
45 nan
46 nan
47 08h00
48 15h30
49 15h01
50 nan
51 Late afternoon
52 nan
55 nan
57 nan
60 13h45
62 nan
63 16h00
64 23h30
65 nan
66 09h00
67 15h00
68 Afternoon
69 17h00
72 09h00
73 14h30
74 18h30
76 nan
77 Morning
78 18h00
79 15h30
80 14h00
81 Morning
82 nan
83 16h30
84 Afternoon
85 Night
87 18h45
88 15h00
89 06h00
90 nan
91 Morning
92 10h00
93 nan
95 10h44
96 10h30
99 nan
100 10h00
101 15h00
102 13h30
104 23h30
105 10h45
106 18h30
107 15h00
110 nan
111 17h00
116 11h20
117 07h45
118 18h30
119 11h45
120 11h00
121 15h30
122 nan
125 19h30
127 Morning
129 10h00
130 12h00
131 nan
133 08h30
135 10h00
136 nan
137 nan
140 Morning
141 nan
142 Morning
143 nan
144 17h00
147 17h10
149 11h15
153 08h50
156 09h00
157 13h30
159 nan
163 nan
165 Afternoon
167 10h00
168 18h30
169 14h30
170 nan
171 nan
173 Morning
174 09h30
175 10h20
176 13h30
178 nan
180 nan
181 13h20
182 14h00
183 12h00
184 13h30
185 Morning
186 07h30
188 12h30
189 18h00
190 17h00
192 07h00
193 09h30
194 nan
195 Afternoon
196 02h00
197 09h00
198 11h00
200 Afternoon
201 Afternoon
202 07h30
203 17h00
204 18h00
206 nan
207 10h30
208 16h00
209 11h30
210 17h30
211 9h00
212 13h00
213 11h00
214 10h43
215 After noon
216 nan
217 nan
219 15h15
221 15h40
223 Late afternoon
224 nan
225 nan
227 15h00
228 14h00
229 17h00
230 16h00
231 nan
232 16h30
233 nan
234 11h30
235 nan
236 nan
237 nan
238 12h00
239 19h05
240 nan
241 nan
242 After noon
246 17h00
247 nan
248 nan
250 nan
251 10h00
252 nan
254 22h00
255 16h20
256 14h34
257 11h00
258 nan
259 15h25
260 14h55
261 06h00
262 nan
264 15h00
265 11h30
266 08h30
268 Morning
269 nan
270 Afternoon
271 16h00
273 15h45
277 Morning
279 15h49
280 Afternoon
281 07h00
282 17h30
283 08h00
284 12h00
285 Morning
286 Morning
287 nan
289 nan
290 nan
291 nan
293 19h00
294 nan
295 11h00
296 nan
298 13h30
299 Afternoon
300 Afternoon
301 Midnight
302 nan
303 19h00
304 16h00
306 nan
307 12h30
309 Late afternoon
310 nan
311 nan
312 14h00
314 09h30 / 10h00
315 nan
316 Morning
317 nan
318 Afternoon
319 11h30
320 Morning
322 Morning
323 07h00
324 nan
325 nan
327 nan
329 10h15
330 Afternoon
332 nan
333 18h15
335 11h00
337 04h00
338 nan
339 14h50
340 15h00
341 14h30
342 13h50
344 19h20
345 11h30
346 11h00
348 10h25
349 nan
350 16h50
351 13h00
352 10h00
353 08h30
354 16h20
356 10h45-11h15
357 16h45
358 15h52
359 12h30
360 07h30
361 nan
362 19h00
363 15h00
364 06h15
366 14h40
367 11h30
368 16h00
370 nan
372 10h00
373 19h45
374 17h10
375 12h30
377 07h30
378 11h00
379 08h00
380 06h00
381 nan
382 nan
383 19h00
385 10h00
386 nan
387 nan
388 nan
389 nan
390 08h45
391 nan
392 nan
394 Evening
395 09h00
396 09h00
397 12h10
398 nan
399 18h05
400 16h00
401 14h40
403 16h00
404 11h00
405 nan
406 11h41
407 12h25
409 nan
410 Morning
411 13h00
412 17h51
416 10h50
418 15h00
421 08h00
423 10h30
424 14h15
425 nan
426 15h00
427 15h00
428 13h00
430 16h30
431 09h45
432 11h00
433 nan
434 09h00
435 07h30
436 Afternoon
437 nan
438 11h00
439 nan
440 nan
441 11h45
442 10h00
443 Morning
444 10h20
445 nan
448 10h00
449 06h45
450 nan
451 05h00
452 03h30
453 nan
454 Afternoon
455 nan
457 13h45
458 nan
459 Night
461 08h00
462 Afternoon
464 Morning
467 11h30
468 Morning
469 nan
470 11h30
471 07h00
472 Sometime between 06h00 & 08hoo
473 nan
474 nan
476 13h00
477 13h30
478 06h30
479 16h30
481 18h00
483 08h00
485 11h15
489 17h20
490 11h30
492 11h00
493 14h00
494 11h30
495 17h30
496 11h00
497 11h30
499 18h45
500 10h45
501 13h00
503 20h00
504 nan
506 nan
508 nan
510 nan
512 nan
514 nan
515 11h10
516 nan
517 nan
519 Afternoon
520 14h00
522 nan
523 13h00
524 14h00
525 nan
526 nan
527 15h00
528 Early afternoon
530 17h50
531 14h30
532 Night
533 nan
534 14h00
535 09h30
536 07h00 - 08h00
537 18h15-18h30
538 nan
539 13h00
540 17h01
541 17h00
542 nan
543 nan
544 17h00
545 09h45
546 Afternoon
549 Morning
552 Morning
553 nan
555 09h30
557 nan
558 nan
561 15h00
562 nan
563 15h30
564 09h57
566 Morning
567 13h50
568 13h30
570 13h30
571 15h00
572 nan
573 nan
574 17h58
575 Morning
577 18h00
578 nan
579 nan
580 16h00
581 Night
582 12h00
583 nan
584 20h30
585 nan
586 nan
587 nan
588 nan
590 11h00
591 08h45
592 nan
593 08h00
594 14h30
595 18h15
596 09h00
597 14h00
599 09h00
600 10h30
601 15h00
602 11h00
603 Afternoon
604 nan
605 15h19
607 16h30
608 10h55
609 18h15
610 15h55
611 11h00
612 Late afternoon
613 11h30
614 10h30
615 08h45
616 15h30
617 10h00
618 11h30
619 10h30
620 13h00
621 Morning
622 15h30
625 16h00
626 16h00
627 13h00
628 nan
629 nan
630 12h00
631 nan
632 23h00
634 20h30
636 15h00
637 13h00
641 17h30
642 nan
643 15h00
645 nan
646 16h05
648 14h10
649 16h45
650 11h15
653 nan
655 nan
657 nan
658 nan
659 nan
660 nan
661 15h30
662 nan
663 12h45
664 12h50
665 14h45
666 Morning
669 nan
670 16h00
671 nan
672 Afternoon
673 nan
674 Evening
675 12h00
676 nan
677 08h20
678 11h15
679 nan
681 14h00
682 10h30
683 nan
684 13h30
685 nan
686 12h00
687 nan
688 nan
689 08h30
690 nan
691 nan
693 nan
694 09h00
695 nan
696 09h00
697 09h00
698 nan
699 nan
700 13h24
702 18h00
703 14h00
704 09h00 - 09h30
705 nan
706 nan
707 nan
708 nan
709 16h30
710 nan
711 10h00
712 14h00
713 12h45
714 10h45
715 nan
716 0830
717 13h20
718 16h45
720 09h40
721 14h50
722 11h40
723 17h30
724 08h30
725 08h10
726 12h00
728 11h00
730 10h30
731 07h30
732 17h00
734 18h30
735 12h00
736 16h30
737 Afternoon
738 15h00
741 12h00
742 Afternoon
743 Just before noon
744 11h30
745 07h56
749 nan
750 15h30
751 Afternoon
752 nan
754 1600
755 17h17
756 nan
757 06h45
758 14h40
759 16h35
760 15h30
761 11h45
762 16h30
763 nan
765 09h05
767 nan
769 08h30
770 16h30
772 19h00
773 15h00
775 nan
776 16h30
777 07h15
778 nan
780 14h20
782 Afternoon
783 Afternoon
784 13h20
785 Morning
786 Morning
787 14h30
789 19h45
791 09h00
792 15h00
793 Morning
794 nan
795 14h30
798 19h28
799 12h30
800 nan
801 12h38
802 nan
803 09h30
804 14h00
806 17h00
807 15h50
809 16h05
810 19h00
812 14h30
813 13h00
814 nan
815 nan
816 14h00
817 16h00
819 12h00
821 Afternoon
822 nan
823 nan
824 16h45
825 15h40
826 nan
827 20h00
828 09h00
829 18h00
830 Early morning
831 18h00
832 12h30
833 nan
834 Dawn
835 05h45
836 nan
837 nan
840 06h00
841 13h30
842 Afternoon
843 nan
844 nan
845 nan
846 Morning
847 nan
848 nan
850 13h25
851 nan
852 16h00
853 nan
854 nan
855 08h10
856 10h30
857 Afternoon
858 nan
859 09h50
860 nan
861 12h25
862 15h00
863 10h00
864 15h00
865 15h30
866 nan
867 11h00
868 12h20
869 Afternoon
871 13h26
872 11h00
873 11h00
874 19h30
876 Morning
877 nan
878 15h30
879 09h11
880 nan
882 16h00
883 Evening
884 15h30
885 Night
886 16h30
887 nan
888 14h00
889 15h30
890 nan
891 nan
892 Night
893 10h00
895 17h00
896 20h30
897 12h30
898 17h00
899 nan
900 14h50
901 10h30
902 13h30
903 10h00
904 12h00
906 13h30
907 Afternoon
908 nan
909 12h15
910 17h30
912 14h30
913 nan
914 nan
915 12h00
918 nan
921 Midday
922 15h30
923 11h00
924 06h30
925 nan
926 nan
927 nan
928 nan
929 15h00
930 15h30
931 Afternoon
932 Morning
933 Afternoon
934 nan
936 17h45
937 nan
938 16h00
941 nan
942 10h45
943 Early afternoon
944 18h30
945 18h20
946 10h40
947 Late afternoon
948 nan
949 nan
951 nan
952 15h00
954 12h30
955 nan
957 15h35
958 AM
959 13h51
961 nan
962 11h00
963 10h55
966 Morning
967 nan
968 13h30
969 Morning
970 nan
971 Night
973 nan
974 15h20
975 nan
976 Afternoon
977 nan
978 08h50
980 13h30
981 nan
983 14h30
984 16h00
985 16h30
986 nan
987 17h00
988 nan
989 12h00
990 nan
991 12h00
992 09h00
993 nan
994 nan
995 09h00
996 08h05
997 nan
1000 08h00
1001 15h00
1002 nan
1004 12h40
1006 nan
1007 16h30
1008 10h35
1010 nan
1011 19h15
1012 nan
1013 nan
1015 12h30
1016 Evening
1017 15h15
1018 nan
1021 17h00
1023 12h00
1024 nan
1025 08h45
1028 16h30
1029 09h30
1031 Afternoon
1032 16h00
1033 10h00
1034 14h00
1035 11h00
1036 Night
1037 11h00
1038 09h30
1040 08h00
1041 nan
1042 15h30
1043 15h00
1044 11h00
1045 15h44
1047 nan
1048 16h30
1049 Evening
1050 07h30
1051 15h15
1054 17h00
1055 06h45
1056 10h15
1057 nan
1058 08h30
1059 11h00
1060 16h30
1061 11h00
1062 07h30
1063 14h30
1064 nan
1065 nan
1066 07h00
1068 13h00
1069 15h30
1070 Morning
1071 16h45
1072 09h30
1074 Afternoon
1075 10h30
1076 Dusk
1077 Morning
1078 nan
1080 17h30
1081 06h00
1083 14h45
1084 nan
1085 11h00
1086 12h50
1087 17h30
1088 nan
1089 nan
1090 nan
1091 21h00
1092 Afternoon
1093 nan
1094 nan
1095 18h30
1096 15h30
1098 Lunchtime
1099 19h00
1100 08h45
1101 10h00
1102 nan
1103 06h15
1105 nan
1110 nan
1111 nan
1112 08h30
1113 11h15
1116 08h45
1117 nan
1118 17h30
1119 nan
1120 nan
1121 nan
1123 20h30
1124 20h30
1125 09h35
1126 10h27
1127 10h16
1128 Afternoon
1129 nan
1131 10h00
1132 Late afternoon
1133 0500
1134 16h00
1135 13h15
1136 nan
1137 08h00
1138 Morning
1139 07h45
1140 16h00
1141 nan
1142 Afternoon
1143 18h45
1144 Early morning
1148 20h00
1149 nan
1150 11h30
1151 13h30
1152 nan
1153 06h45
1154 10h15
1155 17h00
1156 19h30
1157 Before 07h00
1158 nan
1159 11h00
1160 07h30
1161 nan
1162 nan
1163 10h30
1165 16h30
1166 14h00
1167 nan
1168 09h20
1169 nan
1171 10h45
1173 09h00
1175 nan
1176 17h30
1180 nan
1181 11h00
1182 07h00
1183 15h00
1184 nan
1185 20h00
1187 nan
1189 nan
1191 nan
1192 nan
1193 10h00 -- 11h00
1194 17h20
1195 11h00
1196 nan
1197 15h30
1198 12h00
1199 12h00
1200 11h45
1201 11h00
1202 14h30
1203 12h00
1204 16h30
1205 10h30
1206 12h00
1207 12h00
1208 12h00
1209 10h00
1210 Morning
1211 nan
1212 19h20
1213 nan
1214 12h00
1215 11h00
1216 15h00
1218 14h45
1219 nan
1222 14h00
1223 10h30
1224 nan
1225 18h00
1226 nan
1227 15h30
1228 09h00
1230 nan
1232 14h30
1233 13h55
1234 nan
1235 nan
1236 14h00
1239 nan
1240 Afternoon
1241 11h00
1242 14h00
1243 nan
1244 Afternoon
1245 11h15
1246 Morning
1249 nan
1250 nan
1253 15h00
1254 15h50
1255 nan
1256 Early morning
1257 nan
1258 Night
1259 07h30
1260 14h00
1261 Just before noon
1262 nan
1263 Afternoon
1264 11h45
1265 10h30
1266 Morning
1267 09h50
1268 07h00
1269 08h45
1270 nan
1271 nan
1272 Evening
1273 11h00
1274 15h00
1275 nan
1276 nan
1278 08h05
1279 12h00
1280 nan
1281 18h50
1282 nan
1283 11h30
1284 15h53
1285 Afternoon
1286 08h00
1287 10h00
1288 nan
1289 17h00
1291 nan
1292 nan
1293 nan
1294 07h30
1295 nan
1297 nan
1298 nan
1299 nan
1300 nan
1301 nan
1302 11h00
1303 nan
1304 20h30
1305 "Just before 11h00"
1307 nan
1308 nan
1309 14h20
1310 17h30
1311 11h115
1312 09h00
1313 08h45
1314 nan
1315 15h30
1317 12h00
1318 20h30
1319 08h10
1320 11h30
1321 14h40
1328 18h20
1329 Dusk
1330 11h15
1332 16h00
1335 18h30
1337 09h45
1338 16h30
1339 10h45
1340 14h00
1341 Morning
1342 nan
1343 19h45
1344 20h15
1345 12h39
1346 10h00
1347 Night
1349 18h00
1350 16h40
1351 14h00
1353 Afternoon
1354 23h00
1355 nan
1356 10h15
1357 15h15
1358 11h00
1359 12h30
1360 nan
1364 16h00
1365 14h30
1367 nan
1369 17h30
1370 07h05
1373 Sunset
1376 Afternoon
1378 17h45
1380 nan
1381 12h15
1383 08h30
1387 12h30
1388 17h00
1390 16h00
1391 13h05
1392 14h20
1393 13h20
1395 Evening
1397 nan
1399 13h00
1400 nan
1401 nan
1402 08h00
1403 nan
1404 14h00
1406 10h30
1407 nan
1408 Afternoon
1409 06h30
1410 14h00
1411 10h15
1412 20h00
1413 11h00
1414 11h50
1415 "Evening"
1416 07h30
1418 12h30
1419 Afternoon
1420 Just before sundown

1421 nan
1422 11h30
1423 nan
1424 12h00
1427 nan
1428 nan
1429 nan
1430 Morning
1431 14h00
1432 nan
1433 11h00
1434 13h00
1435 17h30
1436 17h55
1437 nan
1438 Sunset
1439 16h00
1440 18h00
1441 nan
1442 nan
1443 nan
1444 11h00
1445 nan
1446 11h00
1448 nan
1450 16h00
1451 Afternoon
1452 nan
1453 16h30
1454 13h45
1455 nan
1457 10h00
1460 nan
1461 17h00
1462 13h00
1464 13h00
1466 nan
1468 Afternoon
1469 13h00
1471 09h00
1472 11h10
1473 15h30
1475 11h30
1476 13h30
1478 16h00
1479 16h30
1480 11h30
1482 12h15
1484 16h30
1485 nan
1486 nan
1488 Afternoon
1489 13h30
1490 17h30
1491 Afternoon
1492 12h30
1493 nan
1495 nan
1496 18h00
1497 17h00
1499 Late afternoon
1500 11h00
1501 nan
1502 12h00
1503 Late afternoon
1505 Afternoon
1506 nan
1507 14h00
1509 22h30
1510 11h00
1511 Morning
1513 16h45
1514 nan
1515 12h00
1516 11h45
1518 11h00
1520 nan
1521 13h00
1523 18h00
1524 11h30
1526 Afternoon
1527 14h30
1529 14h00
1530 13h00
1531 16h45
1532 07h15
1533 nan
1534 08h00
1535 Morning
1536 11h00
1538 17h55
1539 18h00
1541 16h05
1542 nan
1543 15h00
1544 nan
1545 12h05
1546 Morning
1547 07h30
1549 14h00
1550 Dusk
1552 15h00
1553 11h10
1554 nan
1555 16h10
1556 11h00
1557 Afternoon
1558 Morning
1559 20h00
1561 11h30
1562 09h45
1563 nan
1565 11h30
1566 11h15
1567 nan
1568 nan
1570 16h40
1572 11h30
1573 11h30
1576 07h00
1577 08h00
1578 Afternoon
1581 11h00
1582 15h45
1583 Morning
1584 17h30
1586 11h00
1587 nan
1589 nan
1590 nan
1591 10h30
1592 23h00
1594 nan
1595 06h10
1597 nan
1598 19h00
1601 09h45
1602 nan
1603 17h30
1604 14h00
1605 15h30
1606 nan
1607 14h00
1608 nan
1609 nan
1610 nan
1611 14h30
1612 nan
1613 nan
1614 nan
1615 nan
1617 12h00
1619 15h15
1620 13h00
1621 18h00
1622 nan
1625 09h00
1627 14h00
1629 Morning
1630 Afternoon
1631 09h30
1632 12h40
1633 Morning
1634 16h15
1635 15h30
1636 14h00
1638 09h00
1639 Between 05h00 and 08h00
1643 13h00
1644 17h30
1645 16h00
1646 20h30
1647 14h00
1650 nan
1654 19h30
1656 nan
1657 14h10
1659 16h40
1660 09h00
1661 nan
1663 Late afternoon
1664 18h00
1665 15h00
1666 19h45
1667 14h30
1668 11h00
1669 12h30
1670 nan
1673 15h00
1674 16h30
1675 Afternoon
1676 Morning
1678 nan
1679 nan
1680 07h08
1681 14h00
1683 nan
1684 09h00
1685 07h30
1686 15h00
1687 17h00 or 17h40
1688 08h30
1690 12h30
1691 07h45
1692 nan
1693 15h00
1694 19h00
1695 nan
1696 11h00
1697 nan
1698 nan
1699 11h05
1700 nan
1701 nan
1702 14h30
1703 11h00
1704 nan
1705 Midday
1706 nan
1707 Afternoon
1709 Morning
1711 nan
1712 13h15
1713 Night
1714 09h30
1715 11h30
1716 11h30
1717 >08h00
1719 nan
1720 nan
1721 nan
1723 Dusk
1724 nan
1725 15h00
1726 17h30
1728 12h20
1729 12h20
1730 --
1731 --
1733 14h30
1734 14h00
1735 12h02
1737 Night
1738 07h45
1739 11h45
1740 16h30
1741 14h00
1742 16h14
1745 17h11
1746 Afternoon
1747 14h30
1748 nan
1749 12h20
1751 00h30
1752 08h00
1753 nan
1754 15h45
1756 14h30
1757 10h07
1758 nan
1759 14h45
1760 nan
1761 nan
1762 nan
1763 13h53
1764 Morning
1765 nan
1767 08h00
1768 Afternoon
1769 Late afternoon
1772 10h00
1773 13h23
1774 11h45
1775 11h40
1778 nan
1779 18h30
1780 17h00
1781 nan
1782 14h30
1783 13h30
1784 Afternoon
1785 09h00
1786 14h20
1787 13h20
1788 08h50
1789 13h00
1790 --
1791 Dusk
1792 08h00
1794 11h45
1795 Dusk
1796 12h10
1797 --
1798 Morning
1799 --
1800 nan
1803 Just after 12h00
1804 nan
1805 nan
1806 02h30
1807 nan
1808 Afternoon
1809 09h45
1812 13h40
1813 13h25
1814 nan
1816 16h00
1817 Sunset
1818 12h00
1819 13h30
1820 14h35
1821 16h20
1822 07h30
1823 15h35
1824 Afternoon
1825 15h00
1826
1827 Early Morning
1828 15h00
1830 16h00
1831 15h55
1832 17h45
1833 15h45
1835 14h45
1836 15h30
1837 12h30
1838 nan
1839 11h00
1840 19h00
1842 18h45
1843 Shortly after midnight
1844 15h00
1846 10h00
1852 13h00
1853 10h40
1854 13h00
1855
1856 14h15
1857 16h15
1858 17h15
1859 06h47
1860 nan
1861 nan
1862 nan
1863 17h00
1864 nan
1865 12h40
1866 nan
1867 10h30
1868 11h10
1869 18h30
1870 10h45
1871 15h00
1872 11h30
1873 12h00
1875 17h00
1876 15h45
1877 Morning
1878 10h55
1879 nan
1880 nan
1881 09h00 -10h00
1882 20h00
1883 19h15
1884 20h45 (Sunset)
1885 nan
1886 02h00
1888 Sunset
1889 13h00
1890 Morning
1891 nan
1893 nan
1894 nan
1896 Late morning
1897 P.M.
1898 16h20
1899 15h00
1900 13h20
1901 15h00
1902 13h45
1903 nan
1904 nan
1905 18h40
1907 18h00
1909 Afternoon
1910 18h00
1911 13h30
1913 16h20
1914 16h00
1915 14h00
1916 16h20
1917 16h00
1918 13h14
1921 12h30
1922 12h05
1923 10h00
1924 16h00
1925 nan
1927 10h20
1930 16h00
1933 14h30
1934 14h30
1935 Evening
1936 Dusk
1938 18h30
1939 nan
1940 09h00
1941 nan
1943 nan
1944 nan
1945 19h00
1946 nan
1947 nan
1948 nan
1949 17h45
1950 19h00
1951 nan
1952 15h49
1953 11h00
1954 10h55
1955 16h00
1956 16h45
1957 16h05
1958 12h34
1959 11h53
1960 8:04 pm
1961 12h46
1962 07h00
1964 09h30
1965 nan
1966 14h45
1968 10h00
1969 14h40
1970 nan
1971 nan
1972 nan
1976 16h15
1977 nan
1980 nan
1981 nan

In [77]:
sharks.time = sharks.time.str.replace('h', '.')
sharks.time = sharks.time.str.replace('Late afternoon', '17.00')
sharks.time = sharks.time.str.replace('Morning', '07.00')
sharks.time = sharks.time.str.replace('Afternoon', '19.00')
sharks.time = sharks.time.str.replace('Night', '22.00')
sharks.time = sharks.time.str.replace('After noon', '23.00')
sharks.time = sharks.time.str.replace('Midnight', '00.00')
sharks.time = sharks.time.str.replace('09h30 / 10h00', '10.00')
sharks.time = sharks.time.str.replace('10h45-11h15', '11.00')
sharks.time = sharks.time.str.replace('Sometime between 06h00 & 08hoo', '07.00')
sharks.time = sharks.time.str.replace('Early afternoon', '16.00')
sharks.time = sharks.time.str.replace('07h00 - 08h00', '07.00')
sharks.time = sharks.time.str.replace('18h15-18h30', '18.30')
sharks.time = sharks.time.str.replace('09h00 - 09h30', '09.00')
sharks.time = sharks.time.str.replace('0830', '08.30')
sharks.time = sharks.time.str.replace('Just before noon', '23.00')
sharks.time = sharks.time.str.replace('Early morning', '06.00')
sharks.time = sharks.time.str.replace('Midday', '12.00')
sharks.time = sharks.time.str.replace('Dusk', '18.00')
sharks.time = sharks.time.str.replace('Lunchtime', '13.00')
sharks.time = sharks.time.str.replace('Before 07h00', '07.00')
sharks.time = sharks.time.str.replace('10h00 -- 11h00', '10.00')
sharks.time = sharks.time.str.replace('"Just before 11h00"', '11.00')
sharks.time = sharks.time.str.replace('11h115', '11.15')
sharks.time = sharks.time.str.replace('Sunset', '20.00')
sharks.time = sharks.time.str.replace('"Evening"', '20.00')
sharks.time = sharks.time.str.replace('Just before sundown', '05.00')
sharks.time = sharks.time.str.replace('Between 05h00 and 08h00', '07.00')
sharks.time = sharks.time.str.replace('>08h00', '08.00')
sharks.time = sharks.time.str.replace('--', '00.00')
sharks.time = sharks.time.str.replace('Just after 12h00', '12.00')
sharks.time = sharks.time.str.replace('Morning', '07.00')
sharks.time = sharks.time.str.replace('Early Morning', '06.00')
sharks.time = sharks.time.str.replace('Shortly after midnight', '01.00')
sharks.time = sharks.time.str.replace('09h00 -10h00', '09.00')
sharks.time = sharks.time.str.replace('20h45 (Sunset)', '20.45')
sharks.time = sharks.time.str.replace('Late morning', '11.00')
sharks.time = sharks.time.str.replace('P.M.', '17.00')
sharks.time = sharks.time.str.replace('8:04 pm', '20.00')

In [78]:
sharks.time = sharks.time.str.replace('Nig.t', '22.00')
sharks.time = sharks.time.str.replace('Midnig.t', '00.00')
sharks.time = sharks.time.str.replace('09.30 / 10.00', '10.00')
sharks.time = sharks.time.str.replace('10.45-11.15', '11.00')
sharks.time = sharks.time.str.replace('Evening', '20.00')
sharks.time = sharks.time.str.replace('Sometime between 06.00 & 08.oo', '07.00')
sharks.time = sharks.time.str.replace('07.00 - 08.00', '07.00')
sharks.time = sharks.time.str.replace('18.15-18.30', '18.15')
sharks.time = sharks.time.str.replace('09.00 - 09.30', '09.00')
sharks.time = sharks.time.str.replace('Dawn', '06.00')
sharks.time = sharks.time.str.replace('AM', '06.00')
sharks.time = sharks.time.str.replace('Lunc.time', '13.00')
sharks.time = sharks.time.str.replace('0500', '05.00')
sharks.time = sharks.time.str.replace('Before 07.00', '07.00')
sharks.time = sharks.time.str.replace('10.00 00.00 11.00', '10.00')
sharks.time = sharks.time.str.replace('"Just before 11.00"', '11.00')
sharks.time = sharks.time.str.replace('11.115', '11.15')
sharks.time = sharks.time.str.replace('Between 05.00 and 08.00', '07.00')
sharks.time = sharks.time.str.replace('17.00 or 17.40', '17.00')
sharks.time = sharks.time.str.replace('>08.00', '08.00')
sharks.time = sharks.time.str.replace('Just after 12.00', '12.00')
sharks.time = sharks.time.str.replace('Early 07.00', '07.00')
sharks.time = sharks.time.str.replace('S.ortly after midnig.t', '00.00')
sharks.time = sharks.time.str.replace('\xa0 ', '-1.00')
sharks.time = sharks.time.str.replace('09.00 -10.00', '09.00')
sharks.time = sharks.time.str.replace('20.45 (20.00)', '21.00')

In [79]:
sharks[['time']] = sharks[['time']].fillna('-1.00')
sharks.time = sharks.time.str.replace('20.45 (20.00)', '21.00')
sharks.time = sharks.time.str.replace('1600', '16.00')
sharks.time = sharks.time.str.replace(' ', '-1.00')

In [80]:
sharks.time = sharks.time.str.replace('07.00-1.00', '07.00')
sharks.time = sharks.time.str.replace('9.00', '09.00')

In [91]:
horaMal = sharks[sharks.time == '009.00'].index
sharks.loc[horaMal, 'time'] = '09.00'

In [93]:
horaMal2 = sharks[sharks.time == '109.00'].index
sharks.loc[horaMal2, 'time'] = '09.00'

In [95]:
horaMal3 = sharks[sharks.time == '20.45-1.00(20.00)'].index
sharks.loc[horaMal3, 'time'] = '20.00'

In [96]:
print(sharks['time'].unique())

['07.45' '-1.00' '17.00' '14.00' '07.00' '15.00' '08.15' '11.00' '10.30'
 '10.40' '16.50' '09.30' '09.00' '21.50' '09.40' '08.00' '18.00' '17.35'
 '15.30' '07.30' '22.00' '16.00' '15.01' '13.45' '23.30' '14.30' '18.30'
 '16.30' '18.45' '06.00' '10.00' '10.44' '13.30' '10.45' '11.20' '11.45'
 '19.30' '12.00' '08.30' '17.10' '11.15' '08.50' '10.20' '13.20' '12.30'
 '02.00' '11.30' '17.30' '13.00' '10.43' '23.00' '15.15' '15.40' '19.05'
 '16.20' '14.34' '15.25' '14.55' '15.45' '15.49' '00.00' '10.15' '18.15'
 '04.00' '14.50' '13.50' '19.20' '10.25' '16.45' '15.52' '06.15' '14.40'
 '19.45' '08.45' '20.00' '12.10' '18.05' '11.41' '12.25' '17.51' '10.50'
 '14.15' '09.45' '06.45' '05.00' '03.30' '06.30' '17.20' '11.10' '17.50'
 '17.01' '09.57' '17.58' '20.30' '15.19' '10.55' '15.55' '16.05' '14.10'
 '12.45' '12.50' '14.45' '08.20' '13.24' '11.40' '08.10' '07.56' '17.17'
 '16.35' '09.05' '07.15' '14.20' '19.28' '12.38' '15.50' '05.45' '13.25'
 '09.50' '12.20' '13.26' '09.11' '12.15' '17.45' '18.20' '15.35' '13.51'
 '15.20' '08.05' '12.40' '10.35' '19.15' '15.44' '21.00' '09.35' '10.27'
 '10.16' '13.15' '09.20' '13.55' '18.50' '15.53' '20.15' '12.39' '16.40'
 '07.05' '13.05' '11.50' '17.55' '22.30' '12.05' '16.10' '06.10' '16.15'
 '07.08' '11.05' '12.02' '16.14' '17.11' '00.30' '10.07' '13.53' '13.23'
 '02.30' '13.40' '14.35' '17.15' '06.47' '18.40' '13.14' '12.34' '11.53'
 '12.46']

In [98]:
nanCols = sharks.isna().sum()
nanCols[nanCols > 0] # ya no tenemos nulos

Series([], dtype: int64)

In [82]:
sharks.shape, sharks_ori_shape # tamaño del df solo con los datos de los ataques a hombres desde 2001 vs al inicio

((1558, 24), (25723, 24))

Series([], dtype: int64)

In [84]:
sharks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1558 entries, 2 to 1981
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   caseNumber            1558 non-null   object
 1   date                  1558 non-null   object
 2   year                  1558 non-null   float64
 3   type                  1558 non-null   object
 4   country               1558 non-null   object
 5   area                  1558 non-null   object
 6   location              1558 non-null   object
 7   activity              1558 non-null   object
 8   name                  1558 non-null   object
 9   sex                   1558 non-null   object
 10  age                   1558 non-null   object
 11  injury                1558 non-null   object
 12  fatal(y/n)            1558 non-null   object
 13  time                  1558 non-null   object
 14  species               1558 non-null   object
 15  investigatorOrSource  1558 non-null   object
 16  pdf                   1558 non-null   object
 17  hrefFormula           1558 non-null   object
 18  href                  1558 non-null   object
 19  caseNumber1           1558 non-null   object
 20  caseNumber2           1558 non-null   object
 21  originalOrder         1558 non-null   float64
 22  unnamed22             1558 non-null   object
 23  unnamed23             1558 non-null   object
dtypes: float64(2), object(22)
memory usage: 336.6+ KB

In [85]:
['Time', 'pdf','href formula', 'href', 'Case Number.1', 'Case Number.2','original order']

['Time',
 'pdf',
 'href formula',
 'href',
 'Case Number.1',
 'Case Number.2',
 'original order']

In [86]:
sharks.to_csv('../DATA/sharks_clean.csv', sep=',', index=False)

In [87]:
#voy a estudiar los ataques de tiburos desde el año 2001 a 2018 (hasta donde tengo datos) a hombres